### ISSUE TITLE
Multiline fields?

### ISSUE THREAD

**Issue by jdanbrown** [databricks/spark-csv#10]
Any plans to support csv files with multiline fields, i.e. quoted literal newlines? Example:
```
1997,Ford,E350,"Go get one now
they are going fast"
```

As best I understand, hadoop file splits make it impossible in theory—but maybe tractable in practice—to correctly parse multiline fields because you have to start from the beginning of the file to correctly track the state of whether a particular char is inside quotes. Any thoughts on usable practical solutions here?

Our current approach is to `SparkContext.binaryFiles` a bunch of csv files, one task per file, and run a streaming parser over each. The downside of this is of course that our initial RDD partitions are 1-1 with the input csv files, so we have to take care to partition our csv data when we store it.

**Comment by falaki** [comment]
As you mentioned, because for most formats a single file may be split between executors, this cannot be done cleanly. In special cases where individual files are small, SparkContext.wholeTextFile can be used as well.
