### ISSUE TITLE
Issue Saving CSVs in Python

### ISSUE THREAD

**Issue by jspeis** [databricks/spark-csv#101]
Here is a sample CSV file:

    apple,orange
    1,2
    3,4

Now I want to load it in, and save it as a test:

    df = sqlContext.read.format('com.databricks.spark.csv').options(header='true').load('test.csv')
    df.select('apple', 'orange').write.format('com.databricks.spark.csv').save('new_data.csv')

This method however, does not output a CSV but rather a folder containing 3 files: part-00000, part-00001 and  _SUCCESS.

I assume this is an error? I'm using:
Spark 1.4.0
pyspark --packages com.databricks:spark-csv_2.10:1.1.0

**Comment by falaki** [comment]
No this is intended behavior. Spark writes one file per partition and default number of partitions is two. You can change that using repartitioning.

**Comment by jspeis** [comment]
Seems odd though that the API is not designed in a way that the output of save() is valid input for load()?

**Comment by falaki** [comment]
You can pass a directory to ```load()``` function. The output of ```save()``` is valid for ```load()```. Does it not work for you?

**Comment by jspeis** [comment]
Actually it's working perfectly fine - sorry about the confusion!

**Comment by jspeis** [comment]
Works perfectly fine - sorry for the confusion
