### ISSUE TITLE
using spark-csv with a map call

### ISSUE THREAD

**Issue by vats-div** [databricks/spark-csv#115]
I was wondering if there is any way to call the read/write csv inside a map call.  For example, the following code gives an error ```Py4JError: Trying to call a package```
```
data = (sc.parallelize(['cars.csv']).map(
lambda nm: sqlContext.read.format('com.databricks.spark.csv').load(nm)))
data.collect()
```
I tried to do something similar in scala, but got errors as well.

**Comment by brkyvz** [comment]
You can't call it inside an rdd.map function. You may call it for a list and then union those dataframes if you are interested in loading multiple csv files. For example,
```python
files = ['cars.csv', 'other-file.csv']
dfs = [sqlContext.read.format('com.databricks.spark.csv').load(nm) for nm in files]
df = reduce(lambda x, y: x.unionAll(y), dfs)
```

**Comment by vats-div** [comment]
I was calling it using a list comprehension, but didn't realize I could use reduce after that - thanks for the tip!
