### ISSUE TITLE
Charset option (in this case: iso-8859-1) failing in pyshell

### ISSUE THREAD

**Issue by buyology** [databricks/spark-csv#116]
Trying to import files using the `pyspark` shell — encoded in `iso-8859-1`. But they keep on failing me even with **charset** option set to the appropriate encoding — resulting in lots of �'s.

I tried the testfile:
https://raw.githubusercontent.com/databricks/spark-csv/master/src/test/resources/cars_iso-8859-1.csv

**Ran the following:**
`df = sqlContext.read.format('com.databricks.spark.csv').options(header='true',charset='iso-8859-1').load('cars_iso-8859-1.csv.txt')`

**And it still ends up looking like something this:**

> +-----------------------------+
> |year�make�model�comment�blank|
> +-----------------------------+
> |         1997�Ford�E350�"G...|
> |              2015�Chevy�Volt|
> +-----------------------------+

(I do recognize that in _this_ particular case the encoding fails on the delimiters mainly, but it fails generally as well, i.e. within fields too.)

**Comment by falaki** [comment]
@buyology would you please try this with spark-csv version 1.2.0?

**Comment by buyology** [comment]
@falaki Yes, the problem remains. Actually I could only work around this problem by converting files to UTF-8 and then forcing `defaultencoding` in python (because of some reason the problem remained even after conversion…)

    import sys
    reload(sys)
    sys.setdefaultencoding('UTF8')

I suppose there must be a better way.
