### ISSUE TITLE
Write CSV without quotes

### ISSUE THREAD

**Issue by dhirajunraveldata** [databricks/spark-csv#119]
I am looking to write a CSV file with out quotes. Default is ". When I tried it with .option("quotes","") I got error message "only one quote is allowed". 

        If this(writing with out quotes) is not supported in current version any pointers who to implement this would be appreciated.

**Comment by falaki** [comment]
spark-csv does not quote string fields by default. The quote character is used for reading data that include the delimiter inside quotation marks.

**Comment by JoshRosen** [comment]
Related to #89?
