### ISSUE TITLE
scala 2.11.5

### ISSUE THREAD

**Issue by helios** [databricks/spark-csv#13]
How to make it compile with scala 2.11.5 ?
Following Spark https://spark.apache.org/docs/latest/building-spark.html#building-for-scala-211 compiling spark it works.

**Comment by falaki** [comment]
This will come soon. Thanks for filing this issue.

**Comment by eranation** [comment]
Any news? :)

**Comment by falaki** [comment]
Will release 1.0.1 with Scala 2.11 support.
