### ISSUE TITLE
Writing with options such as header, delimiter and quote? 

### ISSUE THREAD

**Issue by buyology** [databricks/spark-csv#136]
Is it possible to access `header`, `delimiter` and `quote` during output?

```
df.write.format("com.databricks.spark.csv").option("header", "true").save("file.csv")
```

yields `'DataFrameWriter' object has no attribute 'option'` and trying to pass them through `options` yields `TypeError: options() takes exactly 1 argument`.

What is the correct syntax? (If implemented.)

**Comment by falaki** [comment]
For PySpark you pass options as last arguments to ```save()```:
```python
save(path=None, source=None, mode='error', **options)
```
See documentation here: http://spark.apache.org/docs/latest/api/python/pyspark.sql.html

**Comment by JoshRosen** [comment]
The `.option()` method was added to the PySpark API in 1.5.0: https://spark.apache.org/docs/1.5.0/api/python/pyspark.sql.html#pyspark.sql.DataFrameWriter.option

**Comment by JoshRosen** [comment]
Is there any action to be take here on the part of `spark-csv`? Do we need to update the documentation / examples?

**Comment by tristanreid** [comment]
The README does list available options with their defaults, and also shows an example of using multiple options - seems clear.
