### ISSUE TITLE
Unable to use the package in Spark shell

### ISSUE THREAD

**Issue by samuel-pt** [databricks/spark-csv#137]
Below are the steps that I did. Started spark-shell using below command

`bin/spark-shell --packages com.databricks:spark-csv_2.10:1.2.0`

In the shell, executed the following scala code

    scala> val hadoopConf = sc.hadoopConfiguration
    scala> hadoopConf.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
    scala> hadoopConf.set("fs.s3.awsAccessKeyId", "****")
    scala> hadoopConf.set("fs.s3.awsSecretAccessKey", "****")

    scala> val s3path = "s3n://bucket/sample.csv"
    scala> val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").load(s3path)

Getting the below error

     java.io.IOException: No FileSystem for scheme: s3n
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:256)
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:207)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
        at scala.Option.getOrElse(Option.scala:120)

What is that I am missing here? Please note that I am able to read the csv using

    scala> sc.textFile(s3path)

The same scala code is working fine in databricks notebook as well

**Comment by yhuai** [comment]
@samuel-pt Can you try set those hadoop conf through 
```
org.apache.spark.deploy.SparkHadoopUtil.get.conf.set(key, value)
```
and see if it works?

**Comment by samuel-pt** [comment]
@yhuai - Still getting the same issue

I've did the following
```
scala> org.apache.spark.deploy.SparkHadoopUtil.get.conf.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
scala> org.apache.spark.deploy.SparkHadoopUtil.get.conf.set("fs.s3.awsAccessKeyId", "xxxx")
scala> org.apache.spark.deploy.SparkHadoopUtil.get.conf.set("fs.s3.awsSecretAccessKey", "xxxxx")
scala> val s3path = "s3n://bucket/sample.csv"
scala> val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").load(s3path)
```

**Comment by samuel-pt** [comment]
@yhuai  - I doubt its an issue with s3 configuration since I am able to load it using sc.textFile(s3path)

**Comment by marmbrus** [comment]
You need to set `fs.s3n.awsAccessKeyId` if you are going to use `s3n`

**Comment by nicolasdalsass** [comment]
Since you use a s3n url, you need to set fs.s3n.impl , not fs.s3.impl.

**Comment by samuel-pt** [comment]
Thanks for pointing it out.

With the below code and with additional jars added in classpath it worked

```
scala> val hadoopConf = sc.hadoopConfiguration
scala> hadoopConf.set("fs.s3n.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
scala> hadoopConf.set("fs.s3n.awsAccessKeyId", "****")
scala> hadoopConf.set("fs.s3n.awsSecretAccessKey", "****")

scala> val s3path = "s3n://bucket/sample.csv"
scala> val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").load(s3path)
```

**Comment by rozhok** [comment]
@samuel-pt how you added libs to classpath? 
What version of Spark and Hadoop you use?

**Comment by alunarbeach** [comment]
running into the same issue thru Jupyter.
@samuel-pt  what are the jars you have added to the classpath and how?

**Comment by rozhok** [comment]
@alunarbeach I had to rebuilt spark adding jets3s and hadoop 2.7.1 libs manually into pom.xml.
Here's some details: http://tech.grammarly.com/blog/posts/Petabyte-Scale-Text-Processing-with-Spark.html
You may download build from https://s3-eu-west-1.amazonaws.com/custom-spark/spark-1.6.0-bin-hadoop2.7.1.tar.gz
