### ISSUE TITLE
DROPMALFORMED should remove rows which do not match the prescribed schema if specified

### ISSUE THREAD

**Issue by kmader** [databricks/spark-csv#162]
My understanding of the parsing mode "DROPMALFORMED" means that it should remove rows which do not match the prescribed schema.
With the following table as a test (test.csv):
```
Name,Age,Height
Bob,10,180
Joe,20.5,200
Tom,30,Dan
```

And the prescribed schema
```scala
val strictSchema = new StructType(
    Array(
      StructField("Name",StringType,true),
      StructField("Age",IntegerType,true),
      StructField("Height",DoubleType,true)
    )
  )
```
The following test should pass.
```scala
val df = new com.databricks.spark.csv.CsvParser()
      .withUseHeader(true).withParseMode("DROPMALFORMED")
      .withSchema(strictSchema).csvFile(sq,"test.csv")
df.count shouldBe 1
```    
Instead the error is given upon execution of the count command
```
Job aborted due to stage failure: Task 1 in stage 50.0 failed 1 times, most recent failure: 
  Lost task 1.0 in stage 50.0 (TID 74, localhost): java.lang.NumberFormatException: For input string: "20.5"
``` 
The error being a problem with parsing the second row "Age" value as an integer.

**Comment by kmader** [comment]
Relevant test cases: https://github.com/databricks/spark-csv/pull/163

**Comment by falaki** [comment]
closed by https://github.com/databricks/spark-csv/pull/163
