### ISSUE TITLE
Problems with loading 'null' value as missing data

### ISSUE THREAD

**Issue by PanWu** [databricks/spark-csv#164]
I am using spark-csv to read data from a table (output from sqoop). The sqoop process treat missing value as 'null', and raw data looks like following: (tab delimited, with missing data)
10001\tapple\t304\tred
10002\tpear\t203\tyellow
10003\tbanana\tnull\tyellow

PROBLEM: If the schema specify the 3rd column is long, spark-csv will raise error exception ('null' is not long type). 

QUESTION: Is it possible to have some "null indicator" in spark-csv, such that user could specify the string "null" represents missing value, and should be replaced into missing value before the actual spark-csv runs?

Thanks!

**Comment by falaki** [comment]
You can specify null value using an option: ```nullValue```

**Comment by PanWu** [comment]
Thanks falaki. However I tried both following command, and it still return the same error. Is this the correct syntax? 

df = sqlContext.read.format('com.databricks.spark.csv').options(header='false', nullValue='null', delimiter='\t').load(data_dir, schema=data_schema)
df = sqlContext.read.format('com.databricks.spark.csv').options(header='false', delimiter='\t').load(data_dir, nullValue='null', schema=data_schema)

The jar file I am using is: spark-csv_2.11-1.2.0.jar.

(I double checked that if I replace 'null' ahead of time, ":%s/null//g", it will load the data correctly)

**Comment by falaki** [comment]
Ah. the new features has not been released yet. It will be in the next version of the JAR that we release. You can use the feature of you compile the project.

**Comment by PanWu** [comment]
I see, it is a great news to have this new feature in next release. Thank you for answering my question!

**Comment by pierre-borckmans** [comment]
@falaki Thanks for your answer. Do you guys have an idea of when you will release this?

**Comment by falaki** [comment]
I just released 1.3.0

**Comment by zhiboz** [comment]
Is it possible to specify multiple nullvalues, like `'null'/'unk'/'unknown'`? Thanks!
