### ISSUE TITLE
Support for pruned scan for required fields.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-csv#166]
As I look through the codes, it looks it reads all the data without pruning by required fields, which i think might improve its performance in particular when the number of requested columns is few but the schema is huge (by io cost and etc.).

I understand that the parser itself parses line by line though.
Is this intentionally unimplemented for some reasons?

**Comment by falaki** [comment]
We always appreciate community contribution.

**Comment by JoshRosen** [comment]
Would this make a performance impact for CSV? Given a row-oriented file format like CSV, how do you save IO / network traffic by skipping reads of certain columns? I can see how column-pruning makes sense for column-oriented file formats, but I don't see an obvious way to do this for CSV.

**Comment by HyukjinKwon** [comment]
There wouldn't be tremendous improvement though. I can see JSONRelatiom in Spark supports this by JacksonParser which supports skip by token.

If we know which position (rather index of fields) to read and parse, I think it can skip token by token (just like JacsonParser) without type checking and read but just move offset and position of the current stream.

**Comment by HyukjinKwon** [comment]
I will close this isuue since this issue is resolved.
