### ISSUE TITLE
Allow configuration of CSV format

### ISSUE THREAD

**Issue by dragos** [databricks/spark-csv#17]
Currently `CSVFormat` is hard coded, but it would be great to allow this to be configured. Probably `CSVFormat.EXCEL` would also be a better default (currently it can't parse CSV exported from Google Docs either). 

It has to do with empty lines. Here is the definition from `apache-commons`:

```
public static final CSVFormat EXCEL = DEFAULT.withIgnoreEmptyLines(false).withAllowMissingColumnNames();
```

**Comment by felixcheung** [comment]
Could I suggest supporting custom delimiter and so on. I understand this is CSV but it is very common to have tab as delimiter (since comma in dataset is very common)

**Comment by felixcheung** [comment]
This would be more methods to allow for customization in implicit class CsvContext

**Comment by falaki** [comment]
We do support custom delimiter character.

**Comment by falaki** [comment]
@dragos Would you please check again to see if you can read Google Docs exported CSV files? We handle empty lines now.
