### ISSUE TITLE
support for transforming dataframe to RDD[String]

### ISSUE THREAD

**Issue by pjfanning** [databricks/spark-csv#188]
Thanks for all the hard work on spark-csv. It is a very useful library, as CSV is a really nice format to get up and running with Spark dataframes.
https://github.com/databricks/spark-csv/commit/2eb90153a2d6a77b9cde4aee3f6e382df3da1746 adds a csvRdd function to create a Dataframe from RDD[String]. It would be useful for me to be able to the reverse.
https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/package.scala saveAsCsvFile already has this but the strRdd is just a temporary internal state used to save the csv to file.
I can put together a pull request with a new function saveAsCsvRdd or convertToCsvRdd if that sounds like an reasonable idea.
Also, is there a plan to publish a new 1.3 release in the near future?

**Comment by pjfanning** [comment]
I have a sample commit at https://github.com/pjfanning/spark-csv/commit/376568acb7f975fe69c26ae790c6792b0d4d002c - I can add more tests if this change is going down the right track

**Comment by falaki** [comment]
Thanks for your suggestion. I just published version 1.3.0.

**Comment by Tagar** [comment]
It would be great to have this built into Spark-CSV or into Spark. Thank you @HyukjinKwon

**Comment by pjfanning** [comment]
I created a pull request: https://github.com/databricks/spark-csv/pull/270
