### ISSUE TITLE
SparkR: object customSchema not found when "manually" loading jars

### ISSUE THREAD

**Issue by VincentLous** [databricks/spark-csv#204]
I think this is a bug on your end, but I am not 100% sure, because I am fairly new to spark.  

I (try to) run SparkR on an enterprise server. I cannot access packages directly from that website, perhaps because of a firewall. In order to use the spark-csv package download this [jar](http://mvnrepository.com/artifact/com.databricks/spark-csv_2.10/1.3.0) and this [jar](http://mvnrepository.com/artifact/org.apache.commons/commons-csv/1.2) and put them in $SPARK_HOME/lib.  

At the moment sparkR.init() only accepts one element for its sparkJars argument, therefore a workaround is to set SPARKR\_SUBMIT\_ARGS environment variable. Solution via this [issue](https://github.com/databricks/spark-csv/issues/59) and this [issue](https://github.com/databricks/spark-csv/issues/79)   

```
Sys.setenv(SPARK_HOME='/somewhere/spark-1.5.1-bin-without-hadoop')
Sys.setenv('SPARKR_SUBMIT_ARGS'='"--jars" "/somewhere/spark-1.5.1-bin-without-hadoop/lib/spark-csv_2.10-1.3.0.jar,/somewhere/spark-1.5.1-bin-without-hadoop/lib/commons-csv-1.2.jar" "sparkr-shell"') 

sc<-sparkR.init(master = "", appName = "vl329b",
  sparkHome = Sys.getenv("SPARK_HOME"))   
```   

This seems to work fine, because I get a message that the jars are loaded and I am able to load the sqlContext afterwards.  Then I try to load a csv file.   

```
tr<-read.df(sqlContext,dataloc, source = "com.databricks.spark.csv", header=TRUE, schema = customSchema, inferSchema = TRUE) 
```
I get the following error. 

> Error in read.df(sqlContext, dataloc, source = "com.databricks.spark.csv",  : 
>  object 'customSchema' not found
>  trace:
> read.df(sqlContext, dataloc, source = "com.databricks.spark.csv", 
>    header = TRUE, schema = customSchema, inferSchema = TRUE)

**Comment by falaki** [comment]
Did you create a customSchema object as suggested by the documentation:
``R
customSchema <- structType(
    structField("year", "integer"),
    structField("make", "string"),
    structField("model", "string"),
    structField("comment", "string"),
    structField("blank", "string"))
```

**Comment by VincentLous** [comment]
Thank you for your response. The documentation in the ReadMe says that is not necessary. My data set is too large to manually add columns and types. 
```
library(SparkR)

Sys.setenv('SPARKR_SUBMIT_ARGS'='"--packages" "com.databricks:spark-csv_2.10:1.3.0" "sparkr-shell"')
sqlContext <- sparkRSQL.init(sc)

df <- read.df(sqlContext, "cars.csv", source = "com.databricks.spark.csv", schema = customSchema, inferSchema = "true")
```

**Comment by falaki** [comment]
In that case, do not specify schema.

**Comment by VincentLous** [comment]
Thank you. I think that needs to be updated in the ReadMe.   

Also, after doing that. I get the below error. Does that have to do with spark-csv?

>
Error in writeJobj(con, object) : invalid jobj 1
trace:
stop("invalid jobj ", value$id)
writeJobj(con, object)
writeObject(con, a)
writeArgs(rc, args)
invokeJava(isStatic = TRUE, className, methodName, ...)
callJStatic("org.apache.spark.sql.api.r.SQLUtils", "loadDF", 
    sqlContext, source, options)
read.df(sqlContext, dataloc, source = "com.databricks.spark.csv", 
    header = TRUE, inferSchema = TRUE)
>
