### ISSUE TITLE
Typo at README.md

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-csv#209]
https://github.com/databricks/spark-csv/commit/cacd8c490d1e656bf9f5cd520bcec0354b3750fd#comments

I added a comment here.

optins should be options. :)

**Comment by rxin** [comment]
Want to submit a pr?

**Comment by HyukjinKwon** [comment]
Well, sure.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-csv/pull/210
