### ISSUE TITLE
Option to add filename / path as a column when loading multiple csv files

### ISSUE THREAD

**Issue by sadikovi** [databricks/spark-csv#212]
I am not sure if such option exists, could not find one to include filename or file path as a column, e.g. `_filename` when loading multiple csv files. Would appreciate, if someone could point out, if such feature exists, otherwise very happy to add it, but need some directions on what to start with. 

For instance:
```shell
local:tmp usr$ ls -lh
-rwxr-xr-x  12 usr  grp   408B 20 Dec 14:04 a.csv
-rwxr-xr-x  12 usr  grp   408B 20 Dec 14:05 b.csv
```

When loading those files to have something like this:
```scala
scala> df.show()
+---+-----+----------+
| C0|   C1| _filename|
+---+-----+----------+
|  1| true|     a.csv|
|  2|false|     a.csv|
|  1| true|     b.csv|
|  2|false|     b.csv|
|  3|false|     b.csv|
+---+-----+----------+
```

**Comment by falaki** [comment]
Unfortunately, we don't have such feature/option in spark-csv.

**Comment by brkyvz** [comment]
Can you load the files one by one, add a column for the filename as you do, and finally union all of them back?

**Comment by sadikovi** [comment]
Potentially, yes. I was thinking if it would be a useful feature to add

**Comment by HyukjinKwon** [comment]
For me I think that might be a narrow use case although this can be useful for some..

**Comment by sadikovi** [comment]
@HyukjinKwon I agree. Anyway, it does not seem to be a very "must-have" option. Workaround with looping through and adding filename works well. Thanks for help, guys, I will close the issue.

**Comment by HyukjinKwon** [comment]
@sadikovi I know it is pretty late but I just found [`input_file_name()`](https://github.com/apache/spark/blob/16df133d7f5f3115cd5baa696fa73a4694f9cba9/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L948) function which can work as below:

```
val data = sqlContext.read.text("/Users/xxxxx...").select(input_file_name)
data.show()
```

```
+--------------------+
|   INPUT_FILE_NAME()|
+--------------------+
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
+--------------------+
```

**Comment by sadikovi** [comment]
@HyukjinKwon Thanks:)
