### ISSUE TITLE
Incorrect type inference

### ISSUE THREAD

**Issue by tanwanirahul** [databricks/spark-csv#216]
Assume the following dataset:

A,B,C,D
1,,,
,1,,
,,1,
,,,1

All the columns ideally should be inferred as Integer/Boolean types. But when we use the spark-csv, here is what we get:

root
 |-- A: integer (nullable = true)
 |-- B: integer (nullable = true)
 |-- C: string (nullable = true)
 |-- D: string (nullable = true)

Columns C & D are inferred as String type. Is this really the expected behavior? Any justification would be helpful.

**Comment by falaki** [comment]
I see space before and after third delimiter. That could be the reason.

**Comment by tanwanirahul** [comment]
If you parse the same csv with SparkContext's textFile, you would get the length of the first records as 7, whilst the rest of them have the length of 4. This indicates there isn't any white space?

**Comment by tanwanirahul** [comment]
Here is another dataset example:

A,B,C,D
1,,1,

and the inferred schema:
root
 |-- A: string (nullable = true)
 |-- B: string (nullable = true)
 |-- C: string (nullable = true)
 |-- D: string (nullable = true)

A & C should be Integers here.

**Comment by tanwanirahul** [comment]
@falaki Could you please check on the use cases shared above and confirm if there is something that needs fix? If there is an issue, I feel it must be resolved ASAP because its very fundamental.

**Comment by falaki** [comment]
Yes, this is a bug. We will hopefully publish a new release with a bug fix. You are more than welcome to submit a fix. The bug is in `InferSchema.scala`

**Comment by tanwanirahul** [comment]
Cool. Have plenty on my plate for the week. Will try to submit by early/mid next week.

**Comment by AEDWIP** [comment]
Thanks Gentlemen. 

Happy New Year

Andy

From:  Rahul <notifications@github.com>
Reply-To:  databricks/spark-csv
<reply+00725a2ffd7390630b0e8afd240275f4cee4ac4dfa2019c592cf00000001129a5fab9
2a169ce075eaca0@reply.github.com>
Date:  Tuesday, December 29, 2015 at 6:50 AM
To:  databricks/spark-csv <spark-csv@noreply.github.com>
Subject:  Re: [spark-csv] Incorrect type inference (#216)

**Comment by tanwanirahul** [comment]
When I use the master branch, the schema inference is working as expected. May be the issue is already fixed. If you remember the pull request that fixed this, would be good to put it into comments. 

For the dataset I shared as a test data:
A,B,C,D
1,,,
,1,,
,,1,
,,,1

I am correctly getting the schema as:
root
 |-- A: integer (nullable = true)
 |-- B: integer (nullable = true)
 |-- C: integer (nullable = true)
 |-- D: integer (nullable = true)

For rest of the cases I shared, the schema is coming up properly.

@falaki , feel free to close/perform any action.

**Comment by HyukjinKwon** [comment]
Hm I think I can work on this maybe within the next week.

**Comment by tanwanirahul** [comment]
I was hit by this error again. This time around, I have more information on the issue. This issue only occurs if we run it with more than one executors. I know where the issue is, and will try submitting the pull for this soon.

**Comment by tanwanirahul** [comment]
Submitted PR for this:  https://github.com/databricks/spark-csv/pull/244

**Comment by HyukjinKwon** [comment]
Could we maybe close this too?

**Comment by tanwanirahul** [comment]
Resolved through #244.
