### ISSUE TITLE
Unnecessarily castng all values in columns when count is performed.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-csv#218]
When we perform count on `DataFrame`, this produces the plan below.

```
== Physical Plan ==
TungstenAggregate(key=[], functions=[(count(1),mode=Final,isDistinct=false)], output=[count#10L])
+- TungstenExchange SinglePartition, None
   +- TungstenAggregate(key=[], functions=[(count(1),mode=Partial,isDistinct=false)], output=[count#14L])
      +- Scan CsvRelation[] ...
```

But thing is, it performs `TableScan` when `requiredColumns` is empty [CsvRelation.scala#L150](https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/CsvRelation.scala#L150), resulting reading and casting all values in the columns. (The performance test proceeded before in the PR https://github.com/databricks/spark-csv/pull/169)

I was thinking of resolving this by letting this return empty rows or explicitly setting any column of schema since the data in CSV is consistent with schema but I am not too sure if this approach is appropriate and even if this should be fixed.

**Comment by yhuai** [comment]
@HyukjinKwon CSV will read all data anyway. So, you meant creating rows containing all column values instead of creating empty rows, right?

**Comment by HyukjinKwon** [comment]
@yhuai It will read all data but does not have to check all the values in rows and convert (cast) them by pruning scan #169 (merged in CSV). 

I think I should change "read" to one such as convert or cast.

And actually I meant empty rows... although I haven't tested yet, doesn't JSON datasource also produce rows in this way?

**Comment by yhuai** [comment]
@HyukjinKwon Yeah, JSON will produce empty rows if no column is needed.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-csv/pull/220
