### ISSUE TITLE
Error upon loading file from hdfs

### ISSUE THREAD

**Issue by aremirata** [databricks/spark-csv#223]
I encountered this error upon reading a file located in hdfs. Do you guys have some idea why this is happening and how we can solve this? 

Py4JJavaError: An error occurred while calling o41.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 4 times, most recent failure: Lost task 1.3 in stage 2.0 (TID 11, 192.168.60.115): java.lang.ClassNotFoundException: com.databricks.spark.csv.CsvRelation$$anonfun$tokenRdd$1

Thank you so much!

**Comment by falaki** [comment]
What version of Spark and spark-csv are you using? How are you loading spark-csv package?

**Comment by AEDWIP** [comment]
Hi Hossein

I am using spark 1.5.2, java


       coalescedSubSetToSave.write()

            .format("com.databricks.spark.csv")

            .option("header", "true")

            .save(outputFile);





This is the version info from my gradle build file. (gradle is a replacement
for maven)



     compile     group: 'com.databricks',   name: 'spark-csv_2.10',
version: '1.3.0'

        testCompile group: 'com.databricks',   name: 'spark-csv_2.10',
version: '1.3.0'


From:  Hossein Falaki <notifications@github.com>
Reply-To:  databricks/spark-csv
<reply+00725a2f12f2e9b189c8031e6d565d92438fb09e7865cca492cf00000001129aa0e29
2a169ce076750ea@reply.github.com>
Date:  Tuesday, December 29, 2015 at 11:28 AM
To:  databricks/spark-csv <spark-csv@noreply.github.com>
Subject:  Re: [spark-csv] Error upon loading file from hdfs (#223)

**Comment by falaki** [comment]
spark-csv depends on apache commons csv and univocity jar files. I suggest you load the package using spark-submit or spark-shell `--packages` flag as suggested in the README.

**Comment by aremirata** [comment]
This is now solved by using the --packages option in starting the kernel. Thank you so much for your replies.

**Comment by aremirata** [comment]
I reopen this issue since spark-csv is now working however, it does not infer the schema. All fields are treated as string. I use Spark-1.5 hadoop 2.6 and the latest version of spark-csv. I use IBM spark-kernel to process this: https://github.com/ibm-et/spark-kernel. What I did is that I add spark-csv as environment variable under Spark options:

{
"display_name": "Spark 1.5.1 (Scala 2.10.4)",
"language_info": { "name": "scala" },
"argv": [
    "/src/spark-kernel/dist/spark-kernel/bin/spark-kernel",
    "--profile",
    "{connection_file}"
],
"codemirror_mode": "scala",
"env": {
    "SPARK_OPTS": "--driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=trace --packages=com.databricks:spark-csv_2.11:1.3.0 ",
    "MAX_INTERPRETER_THREADS": "16",
    "SPARK_CONFIGURATION": "spark.cores.max=4",
    "CAPTURE_STANDARD_OUT": "true",
    "CAPTURE_STANDARD_ERR": "true",
    "SEND_EMPTY_OUTPUT": "false",
    "SPARK_HOME": "/opt/spark",
    "PYTHONPATH": "/opt/spark/python:/opt/spark/python/lib/py4j-0.8.2.1-src.zip"
 }
}
