### ISSUE TITLE
Is v0.2 published on Sonatype or Mavencentral yet

### ISSUE THREAD

**Issue by pierre-borckmans** [databricks/spark-csv#24]
I cannot find it

**Comment by falaki** [comment]
No not yet. Waiting for Spark 1.3 release.

**Comment by elyconn** [comment]
Any chance on this happening now that 1.3 is released?

**Comment by vlyubin** [comment]
@elyconn Will be done within 2 days.

**Comment by vlyubin** [comment]
The version for Spark `1.3` is now published (version number is `1.0.0`). The old versions are still there.

http://search.maven.org/#search%7Cga%7C1%7Cspark-csv
