### ISSUE TITLE
The type org.apache.spark.sql.api.java.JavaSQLContext cannot be resolved. 

### ISSUE THREAD

**Issue by sudev** [databricks/spark-csv#27]
I was not able to find the version `1.0.0` as mentioned in ReadMe through maven.  
```
groupId: com.databricks
artifactId: spark-csv_2.10
version: 1.0.0
```
So, I tried to version `0.1` in my pom.xml. 
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.spark.test</groupId>
	<artifactId>SparkTest</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency> <!-- Spark dependency -->
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.10</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.10</artifactId>
			<version>1.3.0</version>
		</dependency>	
		<dependency>
			<groupId>com.databricks</groupId>
			<artifactId>spark-csv_2.10</artifactId>
			<version>0.1</version>
		</dependency>
	</dependencies>
</project>
```
And when I try to parse a csv, it results in a compilation error. 

`The type org.apache.spark.sql.api.java.JavaSQLContext cannot be resolved. It is indirectly referenced from required .class files`

My Java code        

```{java}
SparkConf conf = new SparkConf();
JavaSparkContext sc = new JavaSparkContext(conf);
SQLContext sqlContext = new org.apache.spark.sql.SQLContext(sc);
DataFrame cars = (new JavaCsvParser()).withUseHeader(true).csvFile(sqlContext , "cars.csv");
```

I'm not able  to understand why the JavaCsvParser is looking for  `org.apache.spark.sql.api.java.JavaSQLContext`, since in `Spark 1.3` they have merged both `JavaSQLContext` and  `SQLContext` into `SQLContext` Again please let me know if I have not configured my pom.xml correctly. 

(I'm new to spark and I'm not sure if I'm talking sense here) 
Thanks

**Comment by falaki** [comment]
We have not officially released version 1.0.0 on Maven. This will be done within coming few days.

**Comment by falaki** [comment]
1.0.0 is released.

**Comment by vinodatpds** [comment]
Hi, 
My pom entries are  : 

<dependencies>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.10</artifactId>
			<version>1.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.hadoop</groupId>
			<artifactId>hadoop-client</artifactId>
			<version>2.7.1</version>
		</dependency>
		<dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.10</artifactId>
            <version>1.3.0</version>
        </dependency>
		<dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-csv_2.11</artifactId>
            <version>1.0.3</version>
        </dependency>
	</dependencies>

I get this error on build : 
[ERROR] COMPILATION ERROR : 
error: cannot find symbol
[ERROR]   symbol:   class DataFrame

The java code where SQLContext & DataFrame is used : 
 private static final SQLContext sqlContext = new SQLContext(sc);
DataFrame cityDF = sqlContext.sql("select CITY,count(*) as Total_Customers from customers group by CITY");

Is it because the jars of spark sql doesnt contain DataFrame ? which is the right sparksql jar i should be using in that case ?

Thanks in advance.

**Comment by brkyvz** [comment]
It's because you are using spark-csv_2.11 but spark-sql_2.10. Could you
also please change 2.11 to 2.10 for spark-Csv?

**Comment by vinodatpds** [comment]
Thanks for the quick reply. 
this didnt work :(
I changed spark-csv to 2.10 to match with spark-sql version 2.10.

<dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.10</artifactId>
            <version>1.3.0</version>
        </dependency>
		<dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-csv_2.10</artifactId>
            <version>1.0.3</version>
        </dependency>

**Comment by brkyvz** [comment]
Could you also match your spark-sql and spark-core version? To 1.4.1
perhaps?

**Comment by brkyvz** [comment]
In fact you don't need spark-core once you have spark-sql.

**Comment by vinodatpds** [comment]
it worked now. Sorry it was a silly miss from my side. I was importing scala.row and other older imports.
i replaced them with these
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.sql.DataFrame;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SQLContext;

@brkyvz Thanks a lot for your replies
