### ISSUE TITLE
Source file name in each row

### ISSUE THREAD

**Issue by ssemichev** [databricks/spark-csv#274]
Is it possible to add a source file name to each row during loading stage?

Thanks

**Comment by falaki** [comment]
Unfortunately it is not possible right now.

**Comment by HyukjinKwon** [comment]
duplicate of https://github.com/databricks/spark-csv/issues/212?

**Comment by ssemichev** [comment]
Yes, the workaround described in  [#212](https://github.com/databricks/spark-csv/issues/212) works well

>> load the files one by one, add a column for the filename and finally union all of them back

**Comment by HyukjinKwon** [comment]
@ssemichev I know it is pretty late but I just found [`input_file_name()`](https://github.com/apache/spark/blob/16df133d7f5f3115cd5baa696fa73a4694f9cba9/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L948) function which can work as below:

```
val data = sqlContext.read.text("/Users/xxxxx...").select(input_file_name)
data.show()
```

```
+--------------------+
|   INPUT_FILE_NAME()|
+--------------------+
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
|file:/Users/xxxxx...|
+--------------------+
```
