### ISSUE TITLE
spark reading nested collections

### ISSUE THREAD

**Issue by premsagarreddy** [databricks/spark-csv#284]
oot
 |-- categoryGuid: string (nullable = true)
 |-- items: struct (nullable = true)
 |    |-- #VALUE: string (nullable = true)
 |    |-- #VALUE: string (nullable = true)
 |    |-- item: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- itemid: string (nullable = true)
 |    |    |    |-- name: string (nullable = true)
 
How to read items.item.name, items.item.name

**Comment by falaki** [comment]
CSV datasource for spark does not support nested data.

**Comment by HyukjinKwon** [comment]
I think this is about `spark-xml` as `spark-csv` does not support nested structure.

**Comment by HyukjinKwon** [comment]
@premsagarreddy Also, if you meant selecting the elements in the array at DataFrame, this might not ne a `spark-csv` or `spark-xml` specific problem. So, I guess you can have a better answer from the user mailing list.

**Comment by premsagarreddy** [comment]
Hi

Thanks for your prompt response.

But how do I select the nested elements in xml using spark xml.

**Comment by premsagarreddy** [comment]
This is like array of elements

**Comment by premsagarreddy** [comment]
I am sorry the issue is related to spark-xml not spark-csv

**Comment by HyukjinKwon** [comment]
@premsagarreddy Can we close this maybe if it was mistakely opened in this repository?

**Comment by premsagarreddy** [comment]
Hi closed the issue,

**Comment by premsagarreddy** [comment]
Hi,

Is the issue about reading nested array xml elements resolved?

**Comment by HyukjinKwon** [comment]
Unfortunately not yet. Let's talk in https://github.com/databricks/spark-xml/issues/91!
