### ISSUE TITLE
Error when using Toree & Jupiter Notebook "Could not initialize class com.databricks.spark.csv.package"

### ISSUE THREAD

**Issue by drizham** [databricks/spark-csv#288]
#### I'm trying to use the cvs reader but am not able to within a Jupyter Notebook:
I know the Spark context within the notebook is working.

#### I am able to add the dependency:
%AddDeps com.databricks spark-csv_2.11 1.4.0
Marking com.databricks:spark-csv_2.11:1.4.0 for download
Preparing to fetch from:
-> file:/tmp/.ivy2/
-> https://repo1.maven.org/maven2
-> New file at /tmp/.ivy2/https/repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.4.0/spark-csv_2.11-1.4.0.jar

#### This is where I am getting stuck:
import org.apache.spark.sql.SQLContext
val sqlContext = new SQLContext(sc)
val df = sqlContext.read.format("com.databricks.spark.csv")
.option("header", "true")
.option("inferSchema", "true")
.load("cars.cv")

#### This is my error (I really have no idea how to decipher this:
Name: java.lang.NoClassDefFoundError
Message: Could not initialize class com.databricks.spark.csv.package$
StackTrace: com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:235)
com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:73)
com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:162)
com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:44)
org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:68)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:73)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:75)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:77)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:79)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:81)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:83)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:85)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:87)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:89)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:91)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:93)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:95)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:97)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:99)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:101)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:103)
$line106.$read$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:105)
$line106.$read$$iwC$$iwC$$iwC$$iwC.<init>(<console>:107)
$line106.$read$$iwC$$iwC$$iwC.<init>(<console>:109)
$line106.$read$$iwC$$iwC.<init>(<console>:111)
$line106.$read$$iwC.<init>(<console>:113)
$line106.$read.<init>(<console>:115)
$line106.$read$.<init>(<console>:119)
$line106.$read$.<clinit>(<console>)
$line106.$eval$.<init>(<console>:7)
$line106.$eval$.<clinit>(<console>)
$line106.$eval.$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:356)
org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:351)
org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:350)
org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:350)
org.apache.toree.utils.TaskManager$$anonfun$add$2$$anon$1.run(TaskManager.scala:140)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by brkyvz** [comment]
Hi,
Are you sure your Spark version is in fact Scala 2.11? Could you also try the dependency:
`com.databricks spark-csv_2.10 1.4.0`?

**Comment by drizham** [comment]
Hi,
I have been trying both actually, just tried `com.databricks spark-csv_2.10 1.4.0` same error.

**Comment by drizham** [comment]
Solved it with
<%AddDeps com.databricks spark-csv_2.10 1.4.0 --transitive>
and
<import org.apache.spark.sql.SQLContext
import sqlContext._
import sqlContext.implicits._
import SQLContext._
val sqlContext = new SQLContext(sc)
import sqlContext.implicits._
val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("cars.csv")>

**Comment by drizham** [comment]
Solved with this import

%AddDeps com.databricks spark-csv_2.10 1.4.0 --transitive

Cell code

import org.apache.spark.sql.SQLContext
import sqlContext._
import sqlContext.implicits._
import SQLContext._
val sqlContext = new SQLContext(sc)
import sqlContext.implicits._
val df = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("cars.cv")

**Comment by dwarakadidam** [comment]
Was curious to know if there is any other way to add the dependency? I'm getting an error. Thanks!

ERROR:root:Line magic function `%AddDeps` not found.
