### ISSUE TITLE
Dataframe to csv IO, system performance enters high CPU state and write operation takes 1 hour to complete instead of 22 seconds

### ISSUE THREAD

**Issue by bigsnarfdude** [databricks/spark-csv#301]
Summary
When using spark-assembly-2.0.0/spark-shell trying to write out results of dataframe to csv, system performance enters high CPU state and write operation takes 1 hour to complete.
Affecting: [Stage 5:> (0 + 2) / 21]
Stage 5 elapsed time 3488272270000ns

In comparison, tests where conducted using Spark 1.4, 1.5, 1.6 with same code/data and Stage5 csv write times where between 2 - 22 seconds.

In addition, as a baseline I  write data to Parquet (Stage 3) using Saprk 1.4, 1.5, 1.6 and 2.0 where similar between 2 - 22 seconds.

CPU profiler points to "com.univocity.parsers.common" which is used in the package? I tried bumping PermGen(1g) and Heap(4g) but it didn't change CPU. Manually dumping GC didn't change anything. I have screenshots and snapshot available. Thoughts?

Files 
1. Data File is "2008.csv"
2. Data file download http://stat-computing.org/dataexpo/2009/the-data.html
3. Code https://gist.github.com/bigsnarfdude/581b780ce85d7aaecbcb

Observation 1 - Setup
./bin/spark-shell --packages com.databricks:spark-csv_2.11:1.4.0 --driver-memory 4g --executor-memory 4g --driver-java-options "-XX:MaxPermSize=1024m"
Stage 5 continued to be 56 minutes. I attached VisualVM and Heap stayed under 2g, and PermGen stayed under 200mb
Code Output: https://gist.github.com/bigsnarfdude/29518daffe4ed77dc5d4
MACOSX 10.11.2 Macbook Pro 16g - 2.2 GHz Intel Core i7 -1TB

Observation 2 - Setup
High CPU and waited over hour for csv write but didnt wait to complete
Ubuntu14.04
4cores 8gb
spark-assembly-2.0.0
spark-csv_2.11-1.4
Code Output: https://gist.github.com/bigsnarfdude/930f5832c231c3d39651

**Comment by falaki** [comment]
@bigsnarfdude thanks for reporting this. I think it is better to report this as a Spark issue. I suspect the bottleneck relates to using univocity for writing CSV in an inefficient way. The spark-csv package uses apache commons for writing CSV.

**Comment by bigsnarfdude** [comment]
I did two CPU snapshots and used a hotspot report pictured here: https://twitter.com/BigsnarfDude/status/712018322749927424

I'm confused, `the com.univocity.common.iput.DefaultCharAppender` is part of this this repo? This is a Apache Spark issue? I'm new to JVM troubleshooting and I'm just getting my head around what is causing the CPU issue.

**Comment by bigsnarfdude** [comment]
Close this issue and open one for Spark.
