### ISSUE TITLE
dateFormat should be used when writing

### ISSUE THREAD

**Issue by barrybecker4** [databricks/spark-csv#308]
This is related to #279

I don't think that the dateFormat specified in the options is used when writing.
Here is what I am doing and it does not write in the specified format:
repartitionDf.write.format("com.databricks.spark.csv")
        .option("delimiter", "\t")
        .option("header", "false")
        .option("nullValue", "?")    // this worked
        .option("dateFormat", "MM/dd/yyyy HH:mm:ss")
        .save(tempFileName)
The file has dates like "2012-01-03 09:12:00.0" but it should be 03/01/2012 09:12:00"

Also, I think it might be risky to use SimpleDateFormat rather than joda's DateTimeFormat, but that could be separate (and I am not sure).

**Comment by HyukjinKwon** [comment]
Indeed. I think it might need to support to write as well. Could I maybe ask why it might be risky?

**Comment by HyukjinKwon** [comment]
Oh, I just checked https://github.com/databricks/spark-csv/issues/279#issuecomment-201036872. It would be okay. AKAIK, That `SimpleDateFormat` object would be created in driver-side once but will be serialised and sent to each task in executer-side, meaning each object in each thread. I think I should double-check though.

**Comment by HyukjinKwon** [comment]
Maybe you can try this code just to double-check. Although it is a bit messy, I think this shows correctly that `simpleDateFormat` object does not affect each task.

```scala
val path = "any-text-file.txt"
val simpleDateFormat = new SimpleDateFormat()
simpleDateFormat.setTimeZone(TimeZone.getTimeZone("Asia/Seoul"))
println(s"Driver-side : ${simpleDateFormat.getTimeZone.getID}")
sparkContext.textFile(path).repartition(3).foreach { _ =>
  println(s"Excuter-side : ${simpleDateFormat.getTimeZone.getID}")
  simpleDateFormat.setTimeZone(TimeZone.getTimeZone("Europe/Copenhagen"))
} 
println(s"Driver-side : ${simpleDateFormat.getTimeZone.getID}")
```

`Excuter-side : Asia/Seoul` will be printed for each partition (can be checked by varying `repartition(#)`, meaning modification in a thread does not affect another.
`Driver-side : Asia/Seoul` will be printed at the end, meaning modification in threads does not affect driver-side.

**Comment by HyukjinKwon** [comment]
@falaki I think I could submit a PR for this if you think it needs.

**Comment by barrybecker4** [comment]
You are probably right and it is safe to use SimpleDateFormatter. I'm not sure I understand enough about how spark works (or will work in the future) to say that the above code will always work. I know that I had tried using it in my spark implementations and ran into problems, so I had to switch to DateTimeFormatter. The thing I worry about is that using a non-threadsafe class in multi-threaded code introduces a risk that may only occur in rare situations, or might cause a problem in the future when other unrelated changes are made. Unfortunately, the pattern language used by SimpleDateFormat is not exactly the same, but I think there is a simple conversion that could be applied by replacing characters within the pattern. 

Looking forward to the fix that allows writing using the specified dateFormat. Thanks for looking into it.

**Comment by barrybecker4** [comment]
I would try to look at fixing this and do a PR, but I'm not sure where the writing is happening. Can you give any pointers on where the fix should go?

**Comment by barrybecker4** [comment]
It looks like it goes in com.databricks.spark/csv/package.scala in CsvSchemaRDD.saveAsCsvFile. The dateFormat would need to be read from the parameters and used for date columns.

**Comment by HyukjinKwon** [comment]
@barrybecker4 Yes, you are right. Maybe you might need to add some additional logics between [this lines](https://github.com/databricks/spark-csv/blob/edf9979c9a03b680390620cb4c367be7232f7875/src/main/scala/com/databricks/spark/csv/package.scala#L163-L164). For other types, `toString` is being called internally. For custom data format, it might need to be handled separately.

For thread-safety, I think it would be great if it has some test codes that produce an exception due to thread-safety if you intend to change `SimpleDateFormat`. If currently you cannot find the case then, I think I'd just leave it as it is.

**Comment by barrybecker4** [comment]
I created a [pull request](https://github.com/databricks/spark-csv/pull/310) for this. Hope someone can give it a review and merge if OK.

**Comment by barrybecker4** [comment]
The pull request to fix this has been merged. Perhaps this can be closed now?

**Comment by falaki** [comment]
Yes, feel free to close the issue.

**Comment by barrybecker4** [comment]
OK. Closing, as the fix has been merged to master.

**Comment by barrybecker4** [comment]
It looks like this change was not ported to spark 2.x. I guess I need to open a jira for spark 2.0 about it.

**Comment by HyukjinKwon** [comment]
Actually, I already did. https://issues.apache.org/jira/browse/SPARK-16216

**Comment by navya35** [comment]
Hello,

I need to know when this fix will be released in next version ?
We need this fix for our developments.

Thanks

**Comment by falaki** [comment]
Sorry for the delay. I just published the last release of the package.

**Comment by navya35** [comment]
Thank you very much for your reactivity
