### ISSUE TITLE
Table name and Options population in CsvRelation

### ISSUE THREAD

**Issue by ashokblend** [databricks/spark-csv#315]
i have created a table in spark with below command. Here i have given extra_option in OPTIONS
create table **tablename** USING com.databricks.spark.csv OPTIONS(path "test.csv",header "true",inferSchema "true", **extra_option "test"**)

insert into table {other table} select * from **tablename** as **aliasname**

While parsing plan, i got CsvRelation as logical relation. From this CsvRelation, i am not able to get **tablename** and **extra_option** and **aliasname**
Is there any way to get this from CsvRelation.

**Comment by HyukjinKwon** [comment]
I believe this library does not support a meta-data-like custom option to allow access. For accessing table and alias, they might not be an issue for this library.

**Comment by ashokblend** [comment]
Ok thank you for response.

**Comment by HyukjinKwon** [comment]
@ashokblend Could we maybe close this for now if you think so?

**Comment by ashokblend** [comment]
we can close it. Thanks.
