### ISSUE TITLE
Unit Test Convenience function for reading in-memory string

### ISSUE THREAD

**Issue by evbo** [databricks/spark-csv#329]
Hi,

for test-driven development purposes, would it make sense to add to the API the ability to `.load()` an inputStream or in-memory String?

This way, Unit tests would be standalone (not relying on flat csv files). 

I understand that much of the functionality of this repository focuses on flat-file parsing, but to test malformed csv it is often a matter of verifying the right `.options` have been set - really nothing to do with the flat-file.

Perhaps this `.load(dummyCsv: String)` convenience function would write the in-memory string to a temp directory and then load it using `.load(tempFile: File)`, or some such abstraction so that the developer only focuses on writing unit tests around this API - rather than focusing on the logistics of filesystems and IO. Unit test directories look a lot cleaner without .csv files hanging around :)

**Comment by HyukjinKwon** [comment]
For me I think we might not need a new API for unit tests. I believe we can just write a function with combination of `parallelize()` to create a rdd and CsvParser API supporting to create a dataframe from rdd here, https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/CsvParser.scala#L150

**Comment by evbo** [comment]
How would you create an RDD that is meant to be derived from malformed csv? In other words, how you can you be sure you're testing how raw comma separated values are parsed correctly if you're already skipping over the parsing of comma delimited data by using an RDD directly?

**Comment by HyukjinKwon** [comment]
Hm.. If I get this correctly, I think this might work for 

> API the ability to .load() an inputStream or in-memory String


```scala
def load(sqlContext: SQLContext, csvData: Seq[String]): DataFrame = {
  val sc = sqlContext.sparkContext
  val rdd = sc.parallelize(csvData)
  CsvParser.csvRdd(sql, rdd)

val csvData = 
  "1,2,3,4" :: 
  "5,6,7,8" ::
  "10,11,13,14" :: Nil

val df = load(sqlContext, csvData)
```

Actually, JSON data source in Spark is using this way for unit tests, (eg. [here](https://github.com/apache/spark/blob/ed0b4070fb50054b1ecf66ff6c32458a4967dfd3/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonSuite.scala#L776-L796)).

**Comment by evbo** [comment]
that code doesn't compile for me (what import are you using for CsvParser).

Assuming it is the Univocity csvParser, you need to specify settings - which are the settings that the spark-csv api is set with. This work around might work, as long as I can tightly couple my spark-csv settings to this CsvParser object (e.g. not set the settings in two different places - production code and unit test code).

**Comment by HyukjinKwon** [comment]
I meant to say it is possible like this. I think this issue might have to be about consistsnt API foramts.

Also, what I wanted to say is, I don't get the reason for creating a new API mainly due to unit tests.

**Comment by evbo** [comment]
yeah, I think my question is confusing because my intention is very specific and I did a bad job focusing on the problem I'm trying to solve.

Essentially, I want to test CSV parsing (and all the `.option()` settings) without referencing actual flat files (to have a more robust test fixture).

For instance, this code would be much cleaner:
```
    val testCsv = "./src/test/scala/some/directory/someTest.csv"
    val parsedCsvData = sqlContext
      .read
      .format("com.databricks.spark.csv")
      .option("header", "true")
      .option("mode", "DROPMALFORMED")
      .option("nullValue", "-")
      .load(testCsv)
      .toDF(column1, column2)

      // Now assert what rows were "dropped" due to malform
```

If it looked like more like your example:

```
val someTestCsvInMemory = 
  "1,2,3,4" :: 
  "5,6,7,8" ::
  "10,11,13,14" :: Nil

val parsedCsvData = sqlContext
      .read
      .format("com.databricks.spark.csv")
      .option("header", "true")
      .option("mode", "DROPMALFORMED")
      .option("nullValue", "-")
      .load(someTestCsvInMemory)
      .toDF(column1, column2)

      // Now assert what rows were "dropped" due to malform
```


The reason why it is cleaner from a test perspective is that the input data is controlled inside an isolated unit test. I could even explicitly define the malformedness like:

```

val aBadRowOfIncorrectColumnCount = "1,2,,,,3,4"
val someTestCsvInMemory = 
  "1,2,3,4" :: 
  "5,6,7,8" ::
  aBadRowOfIncorrectColumnCount ::
  "10,11,13,14" :: Nil
```

Maybe it isn't worth writing a whole new API command, but for what it's worth my reasoning above is why I thought to ask if it were pragmatic to do so.

**Comment by samthebest** [comment]
What's the conclusion of this? It looks to me like `new CsvParser().csvRdd(sqlContext, rdd)` ought to work. You can use the method of `CsvParser` to add the options, e.g. `withUseHeader`.

The import is `import com.databricks.spark.csv.CsvParser`

**Comment by danielrmeyer** [comment]
Could someone help me with a pyspark example that does this, namely parse a csv file that is in memory?  My use case is not testing but I have an encrypted csv file that I need to read into memory and parse.  Ideally I could pass in a StringIO object.  Thanks!

**Comment by RobinL** [comment]
@danielrmeyer  could you share a code sample?

**Comment by danielrmeyer** [comment]
@RobinL here is a small snippet example:
```
from pyspark.sql.types import StringType
from pyspark.sql.types import StructField
import pandas as pd

with open("input.csv", "rb") as input_file:
    csv_data = input_file.read()

cols = csv_data.split()[0].split(',')
schema = StructType([StructField(col, StringType(), True) for col in cols])
data = sqlContext.createDataFrame(pd.read_csv(io.StringIO(csv_data)), samplingRatio=0.5, schema=schema)

```
