### ISSUE TITLE
suggest to use NewHadoopRDD instead of HadoopRDD

### ISSUE THREAD

**Issue by QiangCai** [databricks/spark-csv#337]
suggest to use NewHadoopRDD instead of HadoopRDD.

**Comment by HyukjinKwon** [comment]
Do you mind if I ask what would be advantages of using `NewHadoopRDD` instead of `HadoopRDD`? just curious.

**Comment by QiangCai** [comment]
There are more interface in new API. 
In addition, better to get InputFormat from configure for HadoopRDD/NewHadoopRDD, if default InputFormat class cann't meet requirements.
