### ISSUE TITLE
Spark CSV support for double character delimiter

### ISSUE THREAD

**Issue by nikhilshekhar** [databricks/spark-csv#347]
I was trying out to use a delimiter comprising of two characters, like "::" or a combination of unicode     "Ctrl-ACtrl-B".

But, looks like the delimiter has to be a single character for the parser.

**Comment by liclgo** [comment]
I have the same issue, 
Why not delimiter  can't set to a stringtype

**Comment by falaki** [comment]
The parsers used in this library for CSV parsing require delimiter to be a character.

**Comment by djpirra** [comment]
I am having the same problem and I cannot change the files since they are also used in other processes.
Will this be supported soon?? I think this is a very common usage since sometimes it's not possible to use only one character due to data caracteristics.
