### ISSUE TITLE
Schema unexpectedly persists across reads

### ISSUE THREAD

**Issue by henridf** [databricks/spark-csv#349]
I'm reusing a dataframe reader across reads and noticed that once a schema has been passed in to one `load()`, it continues to be applied on subsequent `load()`'s.

Something like this will repro it:
```
reader = sqlContext.read.format("com.databricks.spark.csv")

df = reader.options(header='true', delimiter='\t').load(inpath, schema=mySchema)
df.write.parquet(outpath)

df = reader.options(header='true', inferSchema=True, delimiter='\t').load(inpath)
df.write.parquet(outpath)
```

If this is an underlying dataframe reader issue, please redirect me and I'll file a Spark JIRA.

**Comment by HyukjinKwon** [comment]
I think this is a Spark issue. `DataFrameReader` holds the options and schema. I think the reader has to be created per-read for now as a workaround.

**Comment by henridf** [comment]
If the schema was passed in to `options()` I could have understood it being persistent, but given that it's passed in to `load()` the reasonable expectation is that it's a per-load thing.

Anyway, thanks for the response. I'll close the issue.

**Comment by HyukjinKwon** [comment]
Just FYI, actually, there is another API in the reader, `.schema(mySchema)`, which sets the schema into `DataFrameReader`.
