### ISSUE TITLE
Spark 2.0.0 Multiple sources found for cvs

### ISSUE THREAD

**Issue by ray6080** [databricks/spark-csv#373]
When using `read().csv("path")`, or `write().csv("path")` in Java, I always encountered _Exception in thread "main" java.lang.RuntimeException: Multiple sources found for cvs.

**Comment by HyukjinKwon** [comment]
This will be a duplicate of https://github.com/databricks/spark-csv/issues/367. We should not import this CSV package. This library was ported into Spark 2.0.
