### ISSUE TITLE
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by MarkRijckenberg** [databricks/spark-csv#38]
Hi,

I have written the following procedure and followed it:

https://mark911.wordpress.com/2015/03/21/how-to-build-pysparkmaven-and-apache-spark-from-github-sources-using-a-bash-script-in-ubuntu-14-04-lts-64-bit/

Importing the csv file via the procedure I wrote, works when using com.databricks:spark-csv version 2.10:1.0.0, but does not work using 2.11:1.0.1. When using 2.11:1.0.1, the Excel header line gets stripped and I need to use the C1 , C2 column names instead of the proper column names in the Excel file.

Is this a new bug in 2.11:1.0.1 ??

Regards,

Mark

**Comment by falaki** [comment]
In version 1.0.1 we changed the default value of header flag from true to false. So if you have a header line in your file, you need to dome something like:
```python
df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv", header = True)
```

**Comment by MarkRijckenberg** [comment]
Thanks for your answer. However, I previously already tried adding header = True and the command only gives an error:

>>> df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv", header = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load() got multiple values for keyword argument 'path'
>>> 

Using path =  without adding header = True also gives an error:

>>> df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load() got multiple values for keyword argument 'path'
>>> 

Here is what I get when I form the command my way and add "header = True" ( error is (py4j.protocol.Py4JJavaError: An error occurred while calling o21.load.
: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String ) )

>>> df = sqlContext.load("cars.csv", "com.databricks.spark.csv", header = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ulysses/spark/python/pyspark/sql/context.py", line 482, in load
    df = self._ssql_ctx.load(source, joptions)
  File "/home/ulysses/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/home/ulysses/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o21.load.
: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:65)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:39)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:27)
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:291)
        at org.apache.spark.sql.SQLContext.load(SQLContext.scala:692)
        at org.apache.spark.sql.SQLContext.load(SQLContext.scala:680)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:207)
        at java.lang.Thread.run(Thread.java:745)

>>> 

Only errors.....

**Comment by MarkRijckenberg** [comment]
Changing the ordering of the arguments to sqlContext.load also generated a similar error:

>>> df = sqlContext.load(source="com.databricks.spark.csv", header=True,path = "cars.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ulysses/spark/python/pyspark/sql/context.py", line 482, in load
    df = self._ssql_ctx.load(source, joptions)
  File "/home/ulysses/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/home/ulysses/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o21.load.
: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:65)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:39)
        at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:27)
        at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:291)
        at org.apache.spark.sql.SQLContext.load(SQLContext.scala:692)
        at org.apache.spark.sql.SQLContext.load(SQLContext.scala:680)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:207)
        at java.lang.Thread.run(Thread.java:745)

>>>

**Comment by falaki** [comment]
Ah, the option should be a string not boolean. Please try: 
```python
df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv", header = "true")
```

**Comment by MarkRijckenberg** [comment]
Thanks a lot! You solved my issue.

The command 

df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv", header = "true")

did not work, but the following command did work using version 2.11:1.0.1 :

>>> df = sqlContext.load(source="com.databricks.spark.csv", header="true",path = "cars.csv") 
15/03/28 19:26:17 INFO MemoryStore: ensureFreeSpace(177238) called with curMem=0, maxMem=278302556
15/03/28 19:26:17 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 173.1 KB, free 265.2 MB)
15/03/28 19:26:17 INFO MemoryStore: ensureFreeSpace(25502) called with curMem=177238, maxMem=278302556
15/03/28 19:26:17 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 24.9 KB, free 265.2 MB)
15/03/28 19:26:17 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:52674 (size: 24.9 KB, free: 265.4 MB)
15/03/28 19:26:17 INFO SparkContext: Created broadcast 2 from textFile at CsvRelation.scala:101
15/03/28 19:26:17 INFO FileInputFormat: Total input paths to process : 1
15/03/28 19:26:17 INFO SparkContext: Starting job: first at CsvRelation.scala:101
15/03/28 19:26:17 INFO DAGScheduler: Got job 1 (first at CsvRelation.scala:101) with 1 output partitions (allowLocal=true)
15/03/28 19:26:17 INFO DAGScheduler: Final stage: Stage 1(first at CsvRelation.scala:101)
15/03/28 19:26:17 INFO DAGScheduler: Parents of final stage: List()
15/03/28 19:26:17 INFO DAGScheduler: Missing parents: List()
15/03/28 19:26:17 INFO DAGScheduler: Submitting Stage 1 (cars.csv MapPartitionsRDD[3] at textFile at CsvRelation.scala:101), which has no missing parents
15/03/28 19:26:17 INFO MemoryStore: ensureFreeSpace(2656) called with curMem=202740, maxMem=278302556
15/03/28 19:26:17 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 2.6 KB, free 265.2 MB)
15/03/28 19:26:17 INFO MemoryStore: ensureFreeSpace(1941) called with curMem=205396, maxMem=278302556
15/03/28 19:26:17 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 1941.0 B, free 265.2 MB)
15/03/28 19:26:17 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on localhost:52674 (size: 1941.0 B, free: 265.4 MB)
15/03/28 19:26:17 INFO SparkContext: Created broadcast 3 from broadcast at DAGScheduler.scala:839
15/03/28 19:26:17 INFO DAGScheduler: Submitting 1 missing tasks from Stage 1 (cars.csv MapPartitionsRDD[3] at textFile at CsvRelation.scala:101)
15/03/28 19:26:17 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
15/03/28 19:26:17 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, PROCESS_LOCAL, 1523 bytes)
15/03/28 19:26:17 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
15/03/28 19:26:17 INFO HadoopRDD: Input split: file:/home/ulysses/spark/cars.csv:0+59
15/03/28 19:26:17 INFO Executor: Finished task 0.0 in stage 1.0 (TID 1). 1824 bytes result sent to driver
15/03/28 19:26:17 INFO DAGScheduler: Stage 1 (first at CsvRelation.scala:101) finished in 0.015 s
15/03/28 19:26:17 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 14 ms on localhost (1/1)
15/03/28 19:26:17 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
15/03/28 19:26:17 INFO DAGScheduler: Job 1 finished: first at CsvRelation.scala:101, took 0.083313 s
>>> df.select("year", "model").show()
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(177238) called with curMem=207337, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 173.1 KB, free 265.0 MB)
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(25502) called with curMem=384575, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 24.9 KB, free 265.0 MB)
15/03/28 19:28:28 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on localhost:52674 (size: 24.9 KB, free: 265.4 MB)
15/03/28 19:28:28 INFO SparkContext: Created broadcast 4 from textFile at CsvRelation.scala:46
15/03/28 19:28:28 INFO FileInputFormat: Total input paths to process : 1
15/03/28 19:28:28 INFO SparkContext: Starting job: runJob at SparkPlan.scala:122
15/03/28 19:28:28 INFO DAGScheduler: Got job 2 (runJob at SparkPlan.scala:122) with 1 output partitions (allowLocal=false)
15/03/28 19:28:28 INFO DAGScheduler: Final stage: Stage 2(runJob at SparkPlan.scala:122)
15/03/28 19:28:28 INFO DAGScheduler: Parents of final stage: List()
15/03/28 19:28:28 INFO DAGScheduler: Missing parents: List()
15/03/28 19:28:28 INFO DAGScheduler: Submitting Stage 2 (MapPartitionsRDD[8] at map at SparkPlan.scala:97), which has no missing parents
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(7192) called with curMem=410077, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_5 stored as values in memory (estimated size 7.0 KB, free 265.0 MB)
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(4909) called with curMem=417269, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_5_piece0 stored as bytes in memory (estimated size 4.8 KB, free 265.0 MB)
15/03/28 19:28:28 INFO BlockManagerInfo: Added broadcast_5_piece0 in memory on localhost:52674 (size: 4.8 KB, free: 265.4 MB)
15/03/28 19:28:28 INFO SparkContext: Created broadcast 5 from broadcast at DAGScheduler.scala:839
15/03/28 19:28:28 INFO DAGScheduler: Submitting 1 missing tasks from Stage 2 (MapPartitionsRDD[8] at map at SparkPlan.scala:97)
15/03/28 19:28:28 INFO TaskSchedulerImpl: Adding task set 2.0 with 1 tasks
15/03/28 19:28:28 INFO TaskSetManager: Starting task 0.0 in stage 2.0 (TID 2, localhost, PROCESS_LOCAL, 1523 bytes)
15/03/28 19:28:28 INFO Executor: Running task 0.0 in stage 2.0 (TID 2)
15/03/28 19:28:28 INFO HadoopRDD: Input split: file:/home/ulysses/spark/cars.csv:0+59
15/03/28 19:28:28 INFO Executor: Finished task 0.0 in stage 2.0 (TID 2). 1951 bytes result sent to driver
15/03/28 19:28:28 INFO TaskSetManager: Finished task 0.0 in stage 2.0 (TID 2) in 37 ms on localhost (1/1)
15/03/28 19:28:28 INFO DAGScheduler: Stage 2 (runJob at SparkPlan.scala:122) finished in 0.038 s
15/03/28 19:28:28 INFO DAGScheduler: Job 2 finished: runJob at SparkPlan.scala:122, took 0.057201 s
15/03/28 19:28:28 INFO TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
15/03/28 19:28:28 INFO SparkContext: Starting job: runJob at SparkPlan.scala:122
15/03/28 19:28:28 INFO DAGScheduler: Got job 3 (runJob at SparkPlan.scala:122) with 1 output partitions (allowLocal=false)
15/03/28 19:28:28 INFO DAGScheduler: Final stage: Stage 3(runJob at SparkPlan.scala:122)
15/03/28 19:28:28 INFO DAGScheduler: Parents of final stage: List()
15/03/28 19:28:28 INFO DAGScheduler: Missing parents: List()
15/03/28 19:28:28 INFO DAGScheduler: Submitting Stage 3 (MapPartitionsRDD[8] at map at SparkPlan.scala:97), which has no missing parents
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(7192) called with curMem=422178, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_6 stored as values in memory (estimated size 7.0 KB, free 265.0 MB)
15/03/28 19:28:28 INFO MemoryStore: ensureFreeSpace(4909) called with curMem=429370, maxMem=278302556
15/03/28 19:28:28 INFO MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 4.8 KB, free 265.0 MB)
15/03/28 19:28:28 INFO BlockManagerInfo: Added broadcast_6_piece0 in memory on localhost:52674 (size: 4.8 KB, free: 265.4 MB)
15/03/28 19:28:28 INFO SparkContext: Created broadcast 6 from broadcast at DAGScheduler.scala:839
15/03/28 19:28:28 INFO DAGScheduler: Submitting 1 missing tasks from Stage 3 (MapPartitionsRDD[8] at map at SparkPlan.scala:97)
15/03/28 19:28:28 INFO TaskSchedulerImpl: Adding task set 3.0 with 1 tasks
15/03/28 19:28:28 INFO TaskSetManager: Starting task 0.0 in stage 3.0 (TID 3, localhost, PROCESS_LOCAL, 1523 bytes)
15/03/28 19:28:28 INFO Executor: Running task 0.0 in stage 3.0 (TID 3)
15/03/28 19:28:28 INFO HadoopRDD: Input split: file:/home/ulysses/spark/cars.csv:59+59
15/03/28 19:28:28 WARN CsvRelation$: Ignoring empty line: 
15/03/28 19:28:28 INFO Executor: Finished task 0.0 in stage 3.0 (TID 3). 1954 bytes result sent to driver
15/03/28 19:28:28 INFO TaskSetManager: Finished task 0.0 in stage 3.0 (TID 3) in 56 ms on localhost (1/1)
15/03/28 19:28:28 INFO TaskSchedulerImpl: Removed TaskSet 3.0, whose tasks have all completed, from pool 
15/03/28 19:28:28 INFO DAGScheduler: Stage 3 (runJob at SparkPlan.scala:122) finished in 0.062 s
15/03/28 19:28:28 INFO DAGScheduler: Job 3 finished: runJob at SparkPlan.scala:122, took 0.082575 s
year model
2012 S    
1997 E350

**Comment by MarkRijckenberg** [comment]
I do suggest updating the documentation in the section "Python API"  and replacing the line

df = sqlContext.load("com.databricks.spark.csv", path = "cars.csv", header = True)

with the line

df = sqlContext.load(source="com.databricks.spark.csv", header="true",path = "cars.csv") 

to avoid future bug reports about this :-)

**Comment by falaki** [comment]
Sure. Thanks for filing this
