### ISSUE TITLE
while writing data frame to file, it is adding escape character before delimiter

### ISSUE THREAD

**Issue by jjaiswal123** [databricks/spark-csv#380]
If I am loading CSV and writing it back to file with comma as delimiter , " double quote as text qualifier and \ back slash as escape character.
Example: one of row in file is like 
"Apo,llo",1, 1234.5, "This is Product description"
Delimiter: ,
Textqualifier: "
escapeCharacter: \
Expected output after saving data to file: "Apo,llo",1, 1234.5, "This is Product description"
actual output: Apo\,llo,1, 1234.5, "This is Product description"

**Comment by HyukjinKwon** [comment]
Have you tried the combinations of options, `quote` and `quoteMode`?

**Comment by jjaiswal123** [comment]
Thanks for your response. after using quoteMode, it is working as expected.
