### ISSUE TITLE
New Option Proposal

### ISSUE THREAD

**Issue by KevinMellott91** [databricks/spark-csv#382]
First of all, I love this library and find it useful on a daily basis. However, I often find myself needing to add a "row number" column to datasets that do not natively contain an identifier.

Do you think it would be appropriate to add a parsing option that would allow spark-csv to do this for me? Perhaps something like "generateRowNumbers"?

If this is something that you feel would fit within the scope of responsibilities for spark-csv, then I will create the functionality as a PR. Please just let me know.

**Comment by HyukjinKwon** [comment]
I guess adding new feature is discouraged as it was ported into Spark.

> NOTE: This functionality has been inlined in Apache Spark 2.x. This package is in maintenance mode and we only accept critical bug fixes.

If you want a unique id, how about using [monotonically_increasing_id()](https://github.com/apache/spark/blob/branch-2.0/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L999)?

**Comment by KevinMellott91** [comment]
Ah yes, that is a good point. Thank you for the recommendation as well, sometimes I forget that the SQL function exists!
