### ISSUE TITLE
CSV escaping not working

### ISSUE THREAD

**Issue by nishblue** [databricks/spark-csv#390]
I am using spark-core version 2.0.1 with Scala 2.11. I have simple code to read a csv file which has \ escapes.

```
val myDA = spark.read
      .option("quote",null)
    .schema(mySchema)
    .csv(filePath)
```

As per documentation \ is default escape for csv reader. But it does not work. Spark is reading \ as part of my data. For Ex: City column in csv file is **north rocks\,au** . I am expecting city column should read in code as **northrocks,au**. But instead spark reads it as **northrocks\** and moves **au** to next column.

I have tried following but did not work:

Explicitly defined escape .option("escape",”\\")
Changed escape to | or : in file and in code
I have tried using spark-csv library
Any one facing same issue? Am I missing something?

Thanks

**Comment by nishblue** [comment]
Interesting finding: Escaping works if data is quoted but not otherwise.

**Comment by falaki** [comment]
Yes, in CSV specification escape applies to the quote character. it is a way to have quote character inside a field value.

**Comment by nishblue** [comment]
Ok. How do you escape a delimiter in the data if there are no quotes used?

**Comment by falaki** [comment]
It has to be quoted. https://tools.ietf.org/html/rfc4180

```
   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.
```

**Comment by nishblue** [comment]
Thank you for prompt response!

**Comment by PVikash** [comment]
Hi Guys,

> It has to be quoted. https://tools.ietf.org/html/rfc4180

Even I do have fields enclosed in double quotes, still, escape option is not working.

Following is my input data file(test.txt):
> first , line
> second " line
> "third line"
> fourth \n line
> fifth \r line
> sixth \ line
> "seventh " line"

Here is my piece of code:
```
val rdd = sc.textFile("D:\\Users\\vipareek\\AdHoc\\test.txt")
val schema = new StructType()
      .add("col1", StringType)
val schemaRDD = rdd.map(x => Row(x.toString))
val df = sqlContext.createDataFrame(schemaRDD, schema)
df.coalesce(1).write.format("com.databricks.spark.csv")
      .option("header", "true")
      .option("quoteMode", "NON_NUMERIC")
      .option("escape", "\\")
      .save("D:\\Users\\vipareek\\Projects\\FCA\\Datastax\\AdHoc\\out")

```
Finally, here is the output:

> "col1"
> "first , line"
> "second "" line"
> """third line"""
> "fourth \n line"
> "fifth \r line"
> "sixth \ line"
> """seventh "" line"""

As per the concept mentioned in this thread, In this output escape character should be \ not " (For the last line i.e. "seventh " line")
Could anyone please suggest something, am I missing anything here or using incorrectly?

**Comment by feimengvungle** [comment]
@PVikash I have same issue on 2.3.1
