### ISSUE TITLE
Spark-csv parsing error

### ISSUE THREAD

**Issue by ArslanSaleem** [databricks/spark-csv#397]
I  have this error while writing csv file in filodb using spark 1.6.2 and spark-csv 1.5.0. Any help related to this.

ERROR CsvRelation$: Exception while parsing line:
19787,"EB8A",14036,3,"58eb844","5305699","NV",1,"1964-03-23","CRL","ROBN"," ADULT","2015-01-22 00:00:00",0,"1324757","81e3a64119","FM","","","","","","","","",1,50,98,98,"2016-01-22 00:00:00","300 WEST "A" STREET FALLON NV 894062947","0","",3,0,"Woods Alessandra",2015,1,"58066","12200X","","green",0,0,0,"N","AFLAC","","2016-01-23",\N.

**Comment by HyukjinKwon** [comment]
Have you checked the quote related options?

**Comment by ArslanSaleem** [comment]
No i have no idea about that, is it .option("Quote","MINIMAL")?

**Comment by ArslanSaleem** [comment]
NO

**Comment by ArslanSaleem** [comment]
.option("Quote","MINIMAL") solved the problem Thanks
