### ISSUE TITLE
Empty file is created for dataframe that has no record

### ISSUE THREAD

**Issue by andrewnet** [databricks/spark-csv#418]
Before Spark 2.0, the databricks spark-csv write a file with only title line if the dataframe doesn't have any record. However, since Spark 2.0, spark-csv write an empty file (i.e. no title line) if the dataframe doesn't have any record. This causes problem since I can't read the file back in this case - I should be able to read it back (the schema) and zero record.

**Comment by sadikovi** [comment]
Hi! Had the same problem, and got around it by using either approaches:
- writing schema file, so you can load DataFrame, this actually infers schema (csvfix1.scala)
- saving headers per empty file (csvfix2.scala)

Code:
https://gist.github.com/sadikovi/e5308e6cb6e681fe08abb58c21632131

Just create file with one of the files in your project. You should be able to use it, like this:
```scala
df.fwrite.csv(...)
...
val df = spark.fread.csv(...)
```

**Comment by sadikovi** [comment]
Not sure if there is a simple fix for this.

**Comment by andrewnet** [comment]
Thanks, the workaround looks promising. With that said, this problem should be fixed in spark-csv, it is not good when you can't read what you wrote with the same library.

**Comment by sadikovi** [comment]
Yes, agree. But this should be reported in Spark, rather than here. `spark-csv` for 1.x only. I saw some PRs that address that in some other ways, e.g. just returning DataFrame with empty schema.

**Comment by andrewnet** [comment]
Oh, didn't realize this is for 1.x only. 
Will report to Spark, thanks.

**Comment by sunny1978** [comment]
This is still happening: with header true or false.
I am still getting 200+ EMPTY Files and 1 Good file. This is impacting us to go live on this API. Please suggest a fix ASAP.
spark-csv_2.10 (1.4.0)
NO LUCK with: spark-csv_2.10 (1.5.0)
Spark: 2
HDP: 2.6.0.3-8 Hortonworks
Run1:
3 executors and 3 core:
Result: 202 Files. 201 Empty Files and 1 Non-Empty File
Run2:
1 executor and 1 core
Result: 202 Files. 201 Empty Files and 1 Non-Empty File

**Comment by sadikovi** [comment]
@sunny1978 Have you tried the fix above? https://gist.github.com/sadikovi/e5308e6cb6e681fe08abb58c21632131#file-csvfix2-scala

It makes it compatible to spark-csv 1.x.
