### ISSUE TITLE
NoSuchMethodError: com.databricks.spark.csv.package$.CsvSchemaRDD(Lorg/apache/spark/sql/Dataset;)Lcom/databricks/spark/csv/package$CsvSchemaRDD;

### ISSUE THREAD

**Issue by molivany** [databricks/spark-csv#424]
I have the following code:

`  val csvParameters: Map[String, String] = Map(("delimiter", "\t"), ("header", "true"))
    myDataFrame.coalesce(1).saveAsCsvFile("/my/hdfs/path", csvParameters)`

Configuration tried (with Spark 2.1.0 on Hadoop):
- com.databricks:spark-csv_2.10:1.4.0 + org.apache.commons:commons-csv:1.2
- com.databricks:spark-csv_2.10:1.4.0 + org.apache.commons:commons-csv:1.4

Error:

> 17/04/06 21:25:49 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: com.databricks.spark.csv.package$.CsvSchemaRDD(Lorg/apache/spark/sql/Dataset;)Lcom/databricks/spark/csv/package$CsvSchemaRDD;
java.lang.NoSuchMethodError: com.databricks.spark.csv.package$.CsvSchemaRDD(Lorg/apache/spark/sql/Dataset;)Lcom/databricks/spark/csv/package$CsvSchemaRDD;
        ...
        ...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)

**Comment by molivany** [comment]
Same issue also with spark-csv_2.10:1.5.0... + commons-csv:14.
The code below works fine instead:
`myDataFrame.coalesce(1).write
    .options(csvParameters)
    .format("com.databricks.spark.csv")
    .save("/my/hdfs/path")`

**Comment by pdendek** [comment]
@molivany
1) I believe spark-csv work on DataFrames so you have to cast your Dataset to DataFrame (dataset.toDF)
2) I believe in Spark 2.x CSV support is enabled by default (no need for additional imports), with some differences to spark-csv avail in 1.6.x- (compare setting header option)
Please try the following:
(myDataFrame
.repartition(1)
.write
.format("csv")
.option("delimiter", "\t")
.option("header",true)
.save("/my/hdfs/path"))

**Comment by molivany** [comment]
Thank you for your quick response!

`csvParameters: Map[String, String] = Map(("delimiter", "\t"), ("header", "true"))`
`myDataFrame.coalesce(1).write.options(csvParameters).csv("/my/hdfs/path")`
