### ISSUE TITLE
CsvRelation should not be protected[spark]

### ISSUE THREAD

**Issue by adefazio** [databricks/spark-csv#43]
Currently the csvFile implicit doesn't expose a way to specify the schema, and since CsvRelation is protected, I can't just call it directly with userSchema set. csvFile should also probably be modified to allow a schema to be passed in as well.

**Comment by falaki** [comment]
You can support a schema using the load() function in SqlContext. csvFile and tsvFile are just there for convenience (in common cases).

**Comment by BobWall23** [comment]
The .load function in SqlContext will handle CSV files directly? It looks like CsvRelation does the parsing of the CSV file - is that code a duplicate of what's in SqlContext.load?

**Comment by falaki** [comment]
You can use SQLContext.load as follows:
```scala
val df = sqlContext.load("com.databricks.spark.csv", Map("path" -> "cars.csv", "header" -> "true"))
```

SQLContext will load the spark-csv package and call appropriate methods to parse data.

**Comment by nlothian** [comment]
Can you show an example of passing a schema to sqlContext.load()?

I have a csv with a header that contains spaces in the column names. spark-csv doesn't seem to handle this well at the moment, and I assume that passing a schema manually is the best work-around?

**Comment by falaki** [comment]
Here is an example for Scala:

``` scala
val sqlContext = new SQLContext(sc);
val schema =
  StructType(
    StructField("a", IntegerType, true) ::
    StructField("b", LongType, false) ::
    StructField("c", BooleanType, false) :: Nil)

val df = sqlContext.load("dbfs://logs/data/", schema, Map("header" -> "true"))
```

Note that the header = true option tells spark-csv  to capture first line of first file and ignore it throughout. 
See the [python API](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.SQLContext.load) for equivalent call in python SQLContext.

**Comment by nlothian** [comment]
Thanks, that makes sense
