### ISSUE TITLE
IncompatibleClassChangeError: Found class org.apache.spark.sql.DataFrame, but interface was expected

### ISSUE THREAD

**Issue by nightscape** [databricks/spark-csv#44]
Hi!

When trying to do a saveAsCsvFile on a DataFrame, I get the following error:
```
java.lang.IncompatibleClassChangeError: Found class org.apache.spark.sql.DataFrame, but interface was expected
	at com.databricks.spark.csv.package$CsvSchemaRDD.saveAsCsvFile(package.scala:60)
...
```
It seems that people face similar problems if they use a different Hadoop version at runtime than the one used to compile.
I'm running the Homebrew-provided spark-shell 1.3.0 locally on my MacBook Air, and I'm not sure if/where Hadoop might be involved in this.

Exporting to parquet works as expected.

I'm thankful for any ideas :)
  Martin

**Comment by yanakad** [comment]
Just chiming in that I observed the same issue. So hopefully this would be an upvote for a fix or a workaround. I don't think compile/runtime Hadoop version is the issue. @nightscape I was able to export a csv file by doing df.map(_.mkString(",")).coalesce(1).saveAsTextFile("foo.csv") but obviously this was out of desperation.

**Comment by rxin** [comment]
Was the brew Spark actually the 1.3.0 release? It seems to me from the error message it might be packaged before the proper release. There was a point in the development cycle when DataFrame was an interface.

**Comment by nightscape** [comment]
@yanakad Thanks for the workaround, I was using a much more complicated DataFrame -> Parquet -> CSV process.
@rxin These are the lines from the brew formula:
```ruby
url "https://d3kbcqa49mib13.cloudfront.net/spark-1.3.0-bin-hadoop2.4.tgz"
version "1.3.0"
sha1 "d94f2847bf92dd6e5a388c8126207cfe57e2c85e"
```
When checking the URL without the filename you get a XML listing with the following entry
```xml
<Contents>
<Key>spark-1.3.0-bin-hadoop2.4.tgz</Key>
<LastModified>2015-03-13T05:38:28.000Z</LastModified>
<ETag>"20dffd5254a2b7e57b76a488cab40cd8"</ETag>
<Size>252761350</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
```

**Comment by rxin** [comment]
What version of Spark-CSV are you using?

**Comment by nightscape** [comment]
I was using 1.0.1 and just wanted to try 1.0.2 but now I'm running into a Spark bug and Spark already hangs when trying to read a CSV...
https://issues.apache.org/jira/browse/SPARK-6640
https://github.com/apache/spark/pull/5306

**Comment by JoshRosen** [comment]
@falaki, is it possible that our published 1.0.1 artifacts were built against a snapshot release that was published locally as 1.3.0, rather than the final 1.3.0 release?

It looks like the published 1.0.1 JAR tries to `invokeinterface` on a DataFrame:

```
javap -classpath ~/.ivy2/cache/com.databricks/spark-csv_2.10/jars/spark-csv_2.10-1.0.1.jar -v com/databricks/spark/csv/package\$CsvSchemaRDD.class
[...]
 public void saveAsCsvFile(java.lang.String, scala.collection.immutable.Map<java.lang.String, java.lang.String>, java.lang.Class<? extends org.apache.hadoop.io.compress.CompressionCodec>);
    flags: ACC_PUBLIC
[...]
        69: aload_0
        70: getfield      #51                 // Field dataFrame:Lorg/apache/spark/sql/DataFrame;
        73: invokeinterface #57,  1           // InterfaceMethod org/apache/spark/sql/DataFrame.columns:()[Ljava/lang/String;
```

This corresponds to the [site of the error](https://github.com/databricks/spark-csv/blob/v1.0.1/src/main/scala/com/databricks/spark/csv/package.scala#L60) reported in the stack trace above.

**Comment by JoshRosen** [comment]
It looks like 1.0.1 [isn't published as a release](http://spark-packages.org/package/databricks/spark-csv) on Spark Packages, but I'm curious to see whether the site's compatibility checker would have caught this incompatibility.  I guess this could depend on whether we run compatibility tests on the binary artifacts retrieved from Maven or on artifacts that we build from source. (/cc @brkyvz )

**Comment by brkyvz** [comment]
We run compatibility tests on artifacts from Maven, if they are supplied. Since 1.0.1 wasn't released on Spark Packages, I ran the api-checker locally. I don't see the IncompatibleClassError, because I can only see differences between Spark 1.3.0 and 1.2.0.

**Comment by rayortigas** [comment]
I tried the spark-csv 1.0.2 artifact and still get the IncompatibleClassChangeError I was getting with 1.0.1.

I downloaded [the JAR proper](http://repo1.maven.org/maven2/com/databricks/spark-csv_2.10/1.0.2/spark-csv_2.10-1.0.2.jar) just to double-check, and got similar javap results for 1.0.2 as @JoshRosen did running javap for 1.0.1.

```
javap -classpath spark-csv_2.10-1.0.2.jar -v com/databricks/spark/csv/package\$CsvSchemaRDD | grep DataFrame
    #7 = Utf8               Lorg/apache/spark/sql/DataFrame;
   #98 = NameAndType        #6:#7         //  dataFrame:Lorg/apache/spark/sql/DataFrame;
   #99 = Fieldref           #2.#98        //  com/databricks/spark/csv/package$CsvSchemaRDD.dataFrame:Lorg/apache/spark/sql/DataFrame;
  #100 = Utf8               org/apache/spark/sql/DataFrame
  #101 = Class              #100          //  org/apache/spark/sql/DataFrame
  #105 = InterfaceMethodref #101.#104     //  org/apache/spark/sql/DataFrame.columns:()[Ljava/lang/String;
  #147 = InterfaceMethodref #101.#146     //  org/apache/spark/sql/DataFrame.rdd:()Lorg/apache/spark/rdd/RDD;
  #225 = Utf8               (Lorg/apache/spark/sql/DataFrame;)V
       237: getfield      #99                 // Field dataFrame:Lorg/apache/spark/sql/DataFrame;
       240: invokeinterface #105,  1          // InterfaceMethod org/apache/spark/sql/DataFrame.columns:()[Ljava/lang/String;
       299: getfield      #99                 // Field dataFrame:Lorg/apache/spark/sql/DataFrame;
       302: invokeinterface #147,  1          // InterfaceMethod org/apache/spark/sql/DataFrame.rdd:()Lorg/apache/spark/rdd/RDD;
  public com.databricks.spark.csv.package$CsvSchemaRDD(org.apache.spark.sql.DataFrame);
         2: putfield      #99                 // Field dataFrame:Lorg/apache/spark/sql/DataFrame;
               0      10     1 dataFrame   Lorg/apache/spark/sql/DataFrame;
```

**Comment by falaki** [comment]
Thanks for verification. I am publishing new jars with fixed dependencies.

**Comment by rayortigas** [comment]
Thank you for publishing the new 1.0.3 jar. It is working for me.

**Comment by falaki** [comment]
Thanks for reporting the issue and following up.

**Comment by yanakad** [comment]
Folks, I am a little late to the party but had a follow up (not sure if this is a bug or I'm misusing)

myDf.saveAsCsvFile("foo.csv") for me now results in a folder with sub-files. The closest I could come up to dumping a csv file is myDf.repartition(1).saveAsCsvFile("foo.csv") and I'm still missing the headers. Additionally the file is still dumped as part-0000 under foo.csv directory.  Is there a simpler way to dump a dataframe with headers and all into a traditional csv file?

**Comment by falaki** [comment]
@yanakad you can pass a Map to saveAsCsvFile as follows:
```scala
myDf.saveAsCsvFile("foo.csv", Map("header" -> "true"))
```
Spark writes each partition into a separate file in the path that you provide (foo.csv/) and there will be a header line on each file.

**Comment by sunshineBoyYHH** [comment]
Hi! I found following erro: 
`Exception in thread "main" java.lang.NoSuchMethodError: com.databricks.spark.csv.package$.CsvSchemaRDD(Lorg/apache/spark/sql/Dataset;)Lcom/databricks/spark/csv/package$CsvSchemaRDD;`

and here is my maven dependency:
`<dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-csv_2.11</artifactId>
            <version>1.5.0</version>
        </dependency>`
I'm thankful for any ideas.

**Comment by molivany** [comment]
@haihuiyang Did you fix it? I'm using spark-csv_2.10:1.4.0
