### ISSUE TITLE
EXTERNAL TABLE SUPPORT

### ISSUE THREAD

**Issue by ssemichev** [databricks/spark-csv#45]
Can you add support for external table for SQL API?

CREATE EXTERNAL TABLE cars
USING com.databricks.spark.csv
OPTIONS (path "cars.csv", header "true")

**Comment by falaki** [comment]
When you specify a path SparkSQL creates the table as external. There is no need for the EXTERNAL keyword.

**Comment by ssemichev** [comment]
If I understand correctly, "CREATE TABLE" command creates Hive internal table.
Internal tables work as immutable tables.

Here is an example how to reproduce it.

Initially my S# bucket has one file only

1) Create table
CREATE TABLE test_table (id string, text string)
USING com.databricks.spark.csv
OPTIONS (path "/mnt/processing/manual_tasks/*", header "true")

2) SELECT count(*) FROM test_table 

3) Add another file to S3 

4) SELECT count(*) FROM test_table   return the same number of row as first SELECT count(*) statement. It means that the new incoming data is not part of the table


If you create a table using "CREATE EXTERNAL TABLE" command, the new incoming data will be part of the table


CREATE EXTERNAL TABLE test_table (id string, text string)
USING com.databricks.spark.csv
OPTIONS (path "/mnt/processing/manual_tasks/*", header "true")

**Comment by falaki** [comment]
SparkSQL caches meta data about tables created using data sources (such as spark-csv), therefore it is necessary to call "REFRESH TABEL" with SparkSQL. Hive does not have this issue because it does not have the metadata cache.

**Comment by ssemichev** [comment]
spark-csv creates an INTERNAL HIVE table
REFRESH TABLE doesn't work also.

CREATE TABLE test_table(id string, text string)
USING com.databricks.spark.csv
OPTIONS (path "/mnt/testdata/*", header "true")
>> OK

DESCRIBE test_table
>> # Registered as a temporary table	null	null
>> id	StringType	null
>> text	StringType

REFRESH TABLE test_table
>>Error in SQL statement: java.lang.RuntimeException: org.apache.spark.sql.hive.HiveQl$ParseException: Failed to parse: REFRESH TABLE test_table

**Comment by falaki** [comment]
Are you running Spark 1.3?

**Comment by ssemichev** [comment]
It's Spark 1.2. Databricks cloud is going to be updated to Spark 1.3 next
week.

On Sat, Apr 4, 2015 at 1:02 AM, Hossein Falaki <notifications@github.com>
wrote:

> Are you running Spark 1.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/databricks/spark-csv/issues/45#issuecomment-89505501>.
>



-- 
Best regards,
Sergey Semichev

**Comment by ssemichev** [comment]
Spark 1.3
"CREATE TABLE" command creates an external Hive table.
New incoming data are visible without "REFRESH TABLE"
"REFRESH TABLE" command works

**Comment by bohemia420** [comment]
No it doesnt for me, dont know where I am wrong : 
1. hdfs.mkdirs('/some/dir')
2. create external table partition on dt loc '/some/dir'
3. spark write in parquet ('/some/dir/dt=20150909')
4. alter table add partition dt = '20150909' etc etc => throws 
alidationFailureSemanticException table is not partitioned but partition spec exists: {dt="20150909"}
