### ISSUE TITLE
Partitions support

### ISSUE THREAD

**Issue by ssemichev** [databricks/spark-csv#50]
Are you planning to add partitions support?

It will be nice to have the similar functionality
CREATE EXTERNAL TABLE baby_names_by_century (
  name STRING,
  gender STRING,
  id STRING
)
PARTITIONED BY
  (date STRING)
ROW FORMAT
  SERDE 'org.apache.hadoop.hive.contrib.serde2.RegexSerDe'
WITH SERDEPROPERTIES
  ("input.regex" = "([^ ]*),([^ ]*),([^ ]*)")
LOCATION
  "path"

**Comment by falaki** [comment]
Yes partition support will be coming to SparkSQL data sources in Spark 1.4. We will update Spark-CSV to support it as well.

**Comment by falaki** [comment]
This was released in Spark 1.4.

**Comment by pchalasani** [comment]
Contrary to what this says, Spark 1.6.1 does NOT seem to have support for partition-discovery for csv sources. Can someone confirm this?

**Comment by HyukjinKwon** [comment]
@pchalasani This CSV library currently does not support that.
(See https://github.com/databricks/spark-csv/issues/123, https://github.com/databricks/spark-csv/issues/197, https://github.com/databricks/spark-csv/issues/106)
