### ISSUE TITLE
Data types not inferred

### ISSUE THREAD

**Issue by lebigot** [databricks/spark-csv#60]
Spark SQL has the ability to infer column types from, say, JSON files. It would be nice if spark-csv did too for CSV files. Currently, in Python at least, all types are strings (with or without header="true").

**Comment by phatak-dev** [comment]
+1

**Comment by trsudarshan** [comment]
+1

**Comment by jsolack** [comment]
+1

**Comment by Looping027** [comment]
+1
(as an alternative, one could at least specify the column types in a parameter of the reading function)

**Comment by falaki** [comment]
Thanks for this feedback. I will work on it.

**Comment by dsdinter** [comment]
+1

**Comment by mnarrell** [comment]
+1 or the ability to provide a StructType?

**Comment by maym86** [comment]
+1
