### ISSUE TITLE
Parsing CSV with '\t' in notebook fails

### ISSUE THREAD

**Issue by falaki** [databricks/spark-csv#65]
```sql
CREATE TABLE tbl_activity_g0_t60_raw
USING com.databricks.spark.csv
options (path "data", header "false", delimiter '\t')
```
Will fail with:
```
"Delimiter cannot be more than one character."
```

**Comment by binarybana** [comment]
I am getting this error even with spark-csv 1.1.0 in a DBC notebook.

I've also tried ``"\t"`` ``\\t`` and other incantations unsuccessfully.

**Comment by vidaha** [comment]
Hi,

It works for me.  Please try these commands in a Python NOtebooK:

dbutils.fs.put("dbfs:/tmp/test.tsv", "col1\tcol2\tcol3\nval1\tval2\tval3\n1\t2\t3\t", True)

print dbutils.fs.head("dbfs:/tmp/test.tsv")

%sql drop table tsv

%sql CREATE TABLE tsv
USING com.databricks.spark.csv
options (path "dbfs:/tmp/test.tsv", header "false", delimiter '\t')

%sql select * from tsv

**Comment by binarybana** [comment]
I can't copy paste from the results of a DBC cell so here's a screenshot: 
![screenshot from 2015-06-18 14-38-53](https://cloud.githubusercontent.com/assets/392846/8242963/f7a3ca8a-15c7-11e5-92d4-212c28717e76.png)
![screenshot from 2015-06-18 14-39-26](https://cloud.githubusercontent.com/assets/392846/8242965/fa95df30-15c7-11e5-94db-9d3e36005f79.png)

**Comment by vidaha** [comment]
1) Can you try checking your cluster and removing any spark-csv jars you have manually installed?  We install this library by default.
2) If this still doesn't work - let's see if you still get their error when you get Databricks 1.4.0, since that's what I tested my notebook on.

**Comment by binarybana** [comment]
Vida, It works now! Not sure if it was the forced cluster reset or the
update, but thanks for all your help. Thanks!

**Comment by binarybana** [comment]
It worked after a cluster reset (and DBC update). Thanks!
