### ISSUE TITLE
Multi-line CSV records ?

### ISSUE THREAD

**Issue by rcongiu** [databricks/spark-csv#72]
CSV format actually permits \n inside a field, as long as it's quoted. So something like

"field1",field 2 that
containts a new line", "field3"

is a valid record, but when I read a CSV file that contains data like that I get
 EOF reached before encapsulated token finished

I realize that is a huge PITA, especially because with text, HDFS splits blocks based on \n regardless of where it is, so to make multi-line CSV records work changing this library is not enough, but also something should be used like the CSVInputFormat here https://github.com/mvallebr/CSVInputFormat/blob/master/src/main/java/org/apache/hadoop/mapreduce/lib/input/CSVLineRecordReader.java

**Comment by falaki** [comment]
Hi @rcongiu this is a good idea. If you like to submit a PR using this reader, would be happy to merge it. In case you are interested, you can also use this old code. https://github.com/falaki/spark/blob/csv/sql/core/src/main/scala/org/apache/spark/sql/csv/CsvTokenizer.scala

Ideally this can be another parserLib that is controlled using options.

**Comment by rxin** [comment]
Does that library actually work? I don't think there is a way to read a CSV file that allows new lines between quotes by starting in the middle, without assuming the maximum record length.

**Comment by falaki** [comment]
Yes, it will be tricky. That was primarily why I abandoned it.

**Comment by rcongiu** [comment]
Thanks, I may take a stab at it... and now that I think about it, @rxin  is right, I don't think there's a 100% safe way to determine if a \n is inside a field or in between records. I guess it would be possible if all the fields were double quoted but that is itself not guaranteed in CSV.
In this particular project I think the best choice is pre-process records so there's one per line, and quote the end of lines.

**Comment by rnowling** [comment]
For Gzipped files, the HadoopInputFormat treats the entire file as a split.  If you are trying to read in many CSV files the performance hit from not being able to parallelize operations on a single file may not be a huge issue.  Thus, you may just write a CSVInputFormat that treats the entire file as a split.

**Comment by rcongiu** [comment]
Thanks..I was thinking the same thing. We ended up just eliminating the problem at the root, that is, CSV is not the best format anyway, and we're pulling data from an external provider through a REST API which returns data in CSV, so instead of doing REST -> local FS -> HDFS we are doing REST -> Kafka -> Parquet instead.

**Comment by JoshRosen** [comment]
Given the discussion above, this seems like a "won't fix" for now.

**Comment by mydpy** [comment]
Can we reopen this? For organizations and software packages using OCR, it's somewhat-frequent to write the text body of a document along with associated metadata as a CSV file. Can we reevaluate if this is something we can fix?

**Comment by HyukjinKwon** [comment]
From Spark 2.2.0 (which I guess will be released soon), there is a `wholeFile` option for this issue. I guess this library will not add additional features anymore but just fix bugs.
