### ISSUE TITLE
How to specify the delimiter?

### ISSUE THREAD

**Issue by rcompton** [databricks/spark-csv#80]
I can't find documentation that shows how save a dataframe as a .tsv rather than a .csv

**Comment by falaki** [comment]
Please take a look at Spark documentation on this: http://spark.apache.org/docs/latest/sql-programming-guide.html#generic-loadsave-functions

For Spark 1.4 you can:
```scala
val df = sqlContext.read.load("examples/src/main/resources/users.parquet")
df.write.format("com.databricks.spark.csv").option("delimiter", "\t").save("users.csv")
```
