### ISSUE TITLE
support for different encodings

### ISSUE THREAD

**Issue by pmackles** [databricks/spark-csv#81]
It looks like spark-csv only supports files encoded in utf8. I am guessing that is due to its use of SparkContext.textFile() which in turn probably uses TextInputFormat (which expects UTF8). 

It looks like the CSVParser in common-csv does allow for specifying different encodings.

I am thinking there might be a way to get spark-csv to support other encodings by:
* exposing an option for encoding
* when that option is not utf8, use SparkContext.hadoopFile() to read the data as binary and then have spark-csv convert it to a String based on the specified encoding before doing the CSV parsing. As per http://stackoverflow.com/questions/15883895/textinputformat-vs-non-utf-8-encoding, it looks like there is a fairly easy way to do this.

If you think the above makes sense, I can work on a PR for the above. The project I am working on needs this no matter what but I would prefer to stick with spark-csv if possible.

**Comment by falaki** [comment]
Hi @pmackles please send the PR. I will review it.

**Comment by pmackles** [comment]
@falaki - thanks. here is a first crack at a PR: https://github.com/databricks/spark-csv/pull/82

**Comment by funnng** [comment]
```
library(SparkR, lib='~/spark/R/lib/')
library(SparkRext)

Sys.setenv('SPARKR_SUBMIT_ARGS'='"--packages" "com.databricks:spark-csv_2.10:1.0.3" "sparkr-shell"')
sc <- sparkR.init(master="local[4]", sparkHome='/Users/13k/spark')
sqlContext = sparkRSQL.init(sc)
```
output：
```
> read.df(sqlContext, '/Users/13k/spark-csv-test-utf8.csv', source = 'com.databricks.spark.csv', charset='UTF8', header='true') %>% collect()
  \0271 \0272 \0273 \0274 \0275
1     1     1     1     1     1
2     2     2     2     2     2
3     3     3     3     3     3
4     4     4     4     4     4
5     5     5     5     5     5
6     -  \x87     W     &     2
> read.df(sqlContext, '/Users/13k/spark-csv-test-gbk.csv', source = 'com.databricks.spark.csv', charset='UTF8', header='true') %>% collect()
  <fd><fd>1 <fd><fd>2 <fd><fd>3 <fd><fd>4 <fd><fd>5
1         1         1         1         1         1
2         2         2         2         2         2
3         3         3         3         3         3
4         4         4         4         4         4
5         5         5         5         5         5
6  \xfd\xfd  \xfd\xfd  \xfd\xfd  \xfd\xfd  \xfd\xfd
```

the csv content(contains some Chinese character):

```
列1,列2,列3,列4,列5
1,1,1,1,1
2,2,2,2,2
3,3,3,3,3
4,4,4,4,4
5,5,5,5,5
中,文,字,符,串
```

it seems that spark-csv still not working well with encoding.

**Comment by pmackles** [comment]
@funnng - so UTF8 is the default charset that is used by Hadoop/Spark. In other words, when the charset is UTF8, the old code path is still used (i.e.SparkContext.textFile()). Are you using newline andor carriage returns to separate records?

**Comment by funnng** [comment]
@pmackles i used returns(\n) to sepatrate records

**Comment by falaki** [comment]
The PR that adds this feature is merged to master but not released yet. I will be cutting a new release soon. Please try again after that.
