### ISSUE TITLE
Loading CSVs into a HiveContext

### ISSUE THREAD

**Issue by junr03** [databricks/spark-csv#88]
In my application I have data coming from CSVs and MSSQL tables. I want to have all these data sources in the same context. The problem is that my SQL queries are too complex for the basic `SQLContext`. Therefore, I decided to move to a `HiveContext`. However, when I do so and try to run my application I am getting an error in when loading the CSVs. 

I executed my application like:
```bash
spark-submit --packages com.databricks:spark-csv_2.11:1.1.0 script.py
````

So when I do
```python
stage_temp = hive_sqlContext.read.format('com.databricks.spark.csv').options(header='true').load('.example.csv')
stage_temp.registerTempTable("example")
```

I get the following error:
```bash
py4j.protocol.Py4JJavaError: An error occurred while calling o24.load.
: java.lang.RuntimeException: Failed to load class for data source: com.databricks.spark.csv
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.sources.ResolvedDataSource$.lookupDataSource(ddl.scala:216)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:229)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConn
```

The same command works when I do the call from an `SQLContext`. I am wondering if spark-csv has no support for HiveContext?

**UPDATE**: I translated the scrip to scala and now the command works with **both** an `SQLContext` and a `HiveContext`.

**Comment by yhuai** [comment]
@junr03 You hit a bug in Spark 1.4.0. It has been fixed in 1.4.1 (it will be released soon). I will add the link to the jira later (seems apache jira is down right now).

**Comment by junr03** [comment]
@yhuai thanks for the comment, I have been trying to figure this out for a long time now. I'll be looking forward to the Jira ticket, and the 1.4.1 push (any estimates?). Thanks!

**Comment by yhuai** [comment]
@junr03 The original problem was reported in https://issues.apache.org/jira/browse/SPARK-8365 and we found the root cause was https://issues.apache.org/jira/browse/SPARK-8368. The fix is in our branch 1.4. For 1.4.1 release, probably later this week or early next week.

**Comment by junr03** [comment]
Thanks!

**Comment by junr03** [comment]
closed by https://github.com/apache/spark/pull/6891

**Comment by Nomii5007** [comment]
@yhuai I am also trying to load CSV into ipython notebook using this script 
```
CV_data = sqlContext.read.load('./data/churn-bigml-80.csv', 
                          format='com.databricks.spark.csv', 
                          header='true', 
                          inferSchema='true')

final_test_data = sqlContext.read.load('./data/churn-bigml-20.csv', 
                          format='com.databricks.spark.csv', 
                          header='true', 
                          inferSchema='true')
CV_data.cache()
CV_data.printSchema() 
```  
but I get error `Py4JJavaError: An error occurred while calling None.org.apache.spark.sql.hive.HiveContext.` `Exception: ("You must build Spark with Hive. Export 'SPARK_HIVE=true' and run build/sbt assembly", Py4JJavaError('An error occurred while calling None.org.apache.spark.sql.hive.HiveContext.\n', JavaObject id=o20))` 
What should I do to resolve this error? I am using latest anaconda distribution and spark 1.5.1 on windows 8.1

**Comment by yhuai** [comment]
How did you build Spark 1.5.1? Did you set `SPARK_HIVE=true`? Can you try to use scala repl and see if there is a problem of creating a HiveContext? Thanks!

**Comment by Nomii5007** [comment]
@yhuai  I just download spark-1.5.1-bin-hadoop2.6 and place it in C:\ and set SPARK_HOME I didnt build it from scratch.'yes I set `SPARK_HIVE=true` it didn't work either. actually I am using ipython notebook (jupyter) I dont know how to use scala repl in it.

**Comment by Nomii5007** [comment]
@yhuai I have another issue if you can solve this HiveContext issue wont matter because I can do it using Sqlcontext. the issue is
I managed to start jupyter notebook with loaded `spark-csv` package by setting this `PYSPARK_DRIVER_PYTHON=ipython` and this  `PYSPARK_DRIVER_PYTHON_OPTS=notebook` as environment variables and then running This command `spark-1.6.1-bin-hadoop2.6\bin\pyspark --packages com.databricks:spark-csv_2.11:1.4.0 --master local[*]` it would start my jupyter notebook but when I type `sc` in cell I get this `‘ ’.`

and when I start my jupyter notebook using this command `ipython notebook --profile=pyspark` or `spark-1.6.1-bin-hadoop2.6\bin\pyspark` and writes `sc` it works perfectly and gives me this `<pyspark.context.SparkContext at 0x584a490>` whats the problem? i want to load spark-csv packge in jupyter notebook.

**Comment by alirezaf1** [comment]
For me it worked when I use 3 slashes /// after file:
df = sqlContext.read.load('file:///home/cloudera/Downloads/big-data-4/daily_weather.csv', 
                          format='com.databricks.spark.csv', header = 'true', inferSchema='true')
