### ISSUE TITLE
Support for disabling CSV quote

### ISSUE THREAD

**Issue by silasdavis** [databricks/spark-csv#89]
I have some tab separated files that may contain all sorts of other characters. I do not want to interpret any character as the quote character, however currently I can't find a way to set it to null, which by the apache commons-csv documentation would disable quoting:

https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html#withQuote(char)

"quoteChar - the quoteChar character, use null to disable"

I'd submit a pull request, but I can't find how the options map gets propagated to the data format package. I've tried:

```scala
sqlContext.createDataFrame(rowRDD, outputSchema)
      .write.format(Constants.CSVDataSource)
      .option("quote", null)
```
But that causes a `NullPointerException`. Can we expose this somehow through `.option("noQuote", "true")` or similar?

**Comment by Michael-Frank** [comment]
+1
I have the same problem since i switched from spark-csv 1.0.3 to 1.1.0 (i had to because of  to spark 1.4 and their new unsafe UTF8 string)

Basically the  1.1.0 version spark-csv ignores the "isNullable"=true flag in StructType, which fails if the DataType !=String. 
```
DataTypes.createStructField("someNullableIntegerColumn", DataTypes.IntegerType, true),
```
This causes the cast to dataType in class com.databricks.spark.csv.CsvRelation, in the following method to fail:
```
private def parseCSV( iter: Iterator[String], csvFormat: CSVFormat,schemaFields: Seq[StructField]): Iterator[Row] = { 
```

Maybe an additional check if "isNullable" in line 198 will do the trick:
```
197:  while (index < schemaFields.length) {
198:    rowArray(index) = TypeCast.castTo(tokens.get(index), schemaFields(index).dataType)
199:     index = index + 1
200:  }
```
Stracktrace:
```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:39)
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:198)
	at com.databricks.spark.csv.CsvRelation$$anonfun$com$databricks$spark$csv$CsvRelation$$parseCSV$1.apply(CsvRelation.scala:180)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation.org$apache$spark$sql$sources$InsertIntoHadoopFsRelation$$writeRows$1(commands.scala:152)
```

**Comment by falaki** [comment]
@silasdavis please take a look at CsvParser.csv. We are not checking if quote is null or not and we pass it to CsvRelation which is then passed to CSVFormat.

**Comment by JoshRosen** [comment]
Related to #119?

**Comment by firemonk9** [comment]
I am wondering if a fix for this issue is in pipeline for the next(1.3) release ?

**Comment by chaotic3quilibrium** [comment]
The way to turn off the default escaping of the double quote character (") with the backslash character (\\) - i.e. to avoid escaping for all characters entirely, you must add an .option() method call with just the right parameters after the .write() method call. The goal of the option() method call is to change how the csv() method "finds" instances of the "quote" character as it is emitting the content. To do this, you must change the default of what a "quote" actually means; i.e. change the character sought from being a double quote character (") to a Unicode "\u0000" character (essentially providing the [Unicode NUL character](https://unicode-table.com/en/) which won't ever occur within a well formed JSON document).

    val dataFrame =
      spark.sql("SELECT * FROM some_table_with_a_json_column")
    val unitEmitCsv =
      dataframe
        .write
        .option("header", true)
        .option("quote", "\u0000") //magic is happening here
        .csv("/FileStore/temp.csv")

This was only one of several lessons I learned attempting to work with Apache Spark and emitting .csv files. For more information and context on this, please see the blog post I wrote titled "[Example Apache Spark ETL Pipeline Integrating a SaaS](http://fromjavatoscala.blogspot.com/2017/03/example-apache-spark-etl-pipeline.html)".

**Comment by nsuguru** [comment]
_.option("quote","\u0000")_ will work if you are using pyspark on Python3 because its default encoding is _'utf-8'._ 
_.option("quote","\u0000")_ will not work if you are using Pyspark with Python2 as its defaulyt encoding is _'ascii'_
